import type { Prisma } from '../../../generated/prisma/index.js';

export const publicMatrimonyProfileSelect = {
  id: true,
  profileFor: true,
  category: true,
  gender: true,
  firstName: true,
  middleName: true,
  lastName: true,
  dateOfBirth: true,
  heightCm: true,
  maritalStatus: true,
  education: true,
  occupation: true,
  companyOrBusiness: true,
  annualIncome: true,
  gotra: true,
  manglik: true,
  birthPlace: true,
  currentCity: true,
  district: true,
  state: true,
  country: true,
  nativePlace: true,
  brothers: true,
  sisters: true,
  about: true,
  isFeatured: true,
  approvedAt: true,
  createdAt: true,
  photos: {
    where: { status: 'APPROVED' },
    orderBy: [{ isPrimary: 'desc' }, { sortOrder: 'asc' }, { createdAt: 'asc' }],
    select: {
      id: true,
      url: true,
      isPrimary: true,
      sortOrder: true,
    },
  },
} satisfies Prisma.MatrimonyProfileSelect;

export const ownerMatrimonyProfileSelect = {
  id: true,
  createdById: true,
  profileFor: true,
  category: true,
  gender: true,
  firstName: true,
  middleName: true,
  lastName: true,
  dateOfBirth: true,
  heightCm: true,
  maritalStatus: true,
  contactPhone: true,
  contactEmail: true,
  education: true,
  occupation: true,
  companyOrBusiness: true,
  annualIncome: true,
  gotra: true,
  manglik: true,
  birthTime: true,
  birthPlace: true,
  currentCity: true,
  district: true,
  state: true,
  country: true,
  fullAddress: true,
  postalCode: true,
  nativePlace: true,
  fatherName: true,
  fatherOccupation: true,
  motherName: true,
  motherOccupation: true,
  brothers: true,
  sisters: true,
  familyDetails: true,
  about: true,
  status: true,
  rejectionReason: true,
  isFeatured: true,
  approvedAt: true,
  createdAt: true,
  updatedAt: true,
  photos: {
    orderBy: [{ isPrimary: 'desc' }, { sortOrder: 'asc' }, { createdAt: 'asc' }],
    select: {
      id: true,
      url: true,
      storageKey: true,
      status: true,
      isPrimary: true,
      sortOrder: true,
      createdAt: true,
    },
  },
  kundalis: {
    orderBy: { createdAt: 'desc' },
    select: {
      id: true,
      fileUrl: true,
      storageKey: true,
      fileName: true,
      mimeType: true,
      status: true,
      createdAt: true,
    },
  },
  partnerPreference: true,
  deleteRequests: {
    where: { status: 'PENDING' },
    orderBy: { createdAt: 'desc' },
    take: 1,
    select: {
      id: true,
      reason: true,
      status: true,
      createdAt: true,
    },
  },
} satisfies Prisma.MatrimonyProfileSelect;
