'use client';
import { useCallback,useEffect,useState } from 'react';
import { useRouter } from 'next/navigation';
import AdminSidebar from '@/components/admin-sidebar';
import { API_BASE_URL,clearAdminSession,getAdminToken,verifyAdminSession } from '@/lib/auth';
type User={id:string;phone:string;email?:string|null;firstName?:string|null;lastName?:string|null;role:'MEMBER'|'ADMIN'|'SUPER_ADMIN';isActive:boolean;lastLoginAt?:string|null;createdAt:string};
async function api(path:string,options:RequestInit={}){const token=getAdminToken();if(!token)throw new Error('SESSION_EXPIRED');const headers:Record<string,string>={authorization:`Bearer ${token}`,accept:'application/json'};if(options.body)headers['content-type']='application/json';const r=await fetch(`${API_BASE_URL}${path}`,{...options,headers:{...headers,...(options.headers||{})},cache:'no-store'});const data=await r.json().catch(()=>({}));if(r.status===401)throw new Error('SESSION_EXPIRED');if(!r.ok)throw new Error(data?.message||data?.error||`Request failed (${r.status})`);return data;}
export default function SettingsPage(){const router=useRouter();const[me,setMe]=useState<any>(null);const[admins,setAdmins]=useState<User[]>([]);const[members,setMembers]=useState<User[]>([]);const[search,setSearch]=useState('');const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState<string|null>(null);
const load=useCallback(async()=>{setLoading(true);setError(null);try{const admin=await verifyAdminSession();if(!admin){router.replace('/login');return;}setMe(admin);const a=await api('/admin/users?status=ACTIVE&role=ALL&page=1&limit=100');setAdmins((a.items||[]).filter((u:User)=>u.role!=='MEMBER'));}catch(e){if(e instanceof Error&&e.message==='SESSION_EXPIRED'){clearAdminSession();router.replace('/login');return;}setError(e instanceof Error?e.message:'Settings load failed');}finally{setLoading(false);}},[router]);useEffect(()=>{void load();},[load]);
async function findMembers(){if(!search.trim()){setMembers([]);return;}setError(null);try{const d=await api(`/admin/users?status=ACTIVE&role=MEMBER&search=${encodeURIComponent(search.trim())}&page=1&limit=20`);setMembers(d.items||[]);}catch(e){setError(e instanceof Error?e.message:'Search failed');}}
async function changeRole(user:User,role:'MEMBER'|'ADMIN'){const label=role==='ADMIN'?'Admin access दें':'Admin access हटाएँ';if(!confirm(`${user.firstName||user.phone} को ${label}?`))return;setBusy(user.id);setError(null);try{await api(`/admin/users/${user.id}/role`,{method:'POST',body:JSON.stringify({role})});setMembers([]);setSearch('');await load();}catch(e){setError(e instanceof Error?e.message:'Role update failed');}finally{setBusy(null);}}
const superAdmin=me?.role==='SUPER_ADMIN';return <div className="admin-shell"><AdminSidebar/><main className="main moderation-page"><div className="moderation-top"><div><p className="eyebrow">ADMINISTRATION</p><h1>Settings</h1><p className="subtitle">Admin access और portal configuration को सुरक्षित तरीके से manage करें।</p></div></div>{error?<div className="moderation-error">{error}</div>:null}<section className="moderation-list"><article className="moderation-card"><h2>Admin Users</h2><p className="subtitle">SUPER_ADMIN ही member को Admin बना या existing Admin को Member कर सकता है।</p>{loading?<div className="empty-state">Loading…</div>:admins.map(u=><div className="reason-box" key={u.id} style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:16}}><div><b>{[u.firstName,u.lastName].filter(Boolean).join(' ')||u.phone}</b><p>{u.phone} • {u.role}{u.lastLoginAt?` • Last login ${new Date(u.lastLoginAt).toLocaleString('en-IN')}`:''}</p></div>{superAdmin&&u.role==='ADMIN'&&u.id!==me?.id?<button disabled={busy===u.id} className="reject-action" onClick={()=>void changeRole(u,'MEMBER')}>Remove Admin</button>:null}</div>)}</article><article className="moderation-card"><h2>Add Admin</h2>{superAdmin?<><p className="subtitle">Existing active member को mobile, name या email से खोजें। नया account यहाँ create नहीं किया जाता।</p><div style={{display:'flex',gap:10,maxWidth:650}}><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();void findMembers();}}} placeholder="Member search करें" style={{flex:1,padding:'12px 14px',border:'1px solid #dfd3bd',borderRadius:10}}/><button className="small-btn" onClick={()=>void findMembers()}>Search</button></div>{members.map(u=><div className="reason-box" key={u.id} style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:16}}><div><b>{[u.firstName,u.lastName].filter(Boolean).join(' ')||u.phone}</b><p>{u.phone}{u.email?` • ${u.email}`:''}</p></div><button disabled={busy===u.id} className="approve-action" onClick={()=>void changeRole(u,'ADMIN')}>Make Admin</button></div>)}</>:<div className="empty-state">Admin list देख सकते हैं, लेकिन role changes के लिए SUPER_ADMIN access चाहिए।</div>}</article><article className="moderation-card"><h2>App Configuration</h2><div className="reason-box"><b>Approval-first publishing</b><p>Community, Matrimony, Samiti और Advertisements moderation workflow enabled है।</p></div><div className="reason-box"><b>Advanced configuration</b><p>Feature flags, limits और monetization settings बाद के phase में database-backed configuration के साथ जोड़े जाएंगे। अभी fake toggles नहीं रखे गए हैं।</p></div></article></section></main></div>}
