import { StyleSheet } from 'react-native';

export const C = {
  bg: '#FFF8ED',
  paper: '#FFFFFF',
  maroon: '#A30D1E',
  maroonDark: '#77101B',
  gold: '#D99A2B',
  text: '#2A211D',
  muted: '#736660',
  line: '#E8DCCF',
  green: '#16865C',
  red: '#B42318',
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: C.bg },
  content: { padding: 17, paddingBottom: 110 },
  headerRow: { flexDirection: 'row', gap: 11, alignItems: 'flex-start', marginBottom: 15 },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.paper,
    borderWidth: 1,
    borderColor: C.line,
  },
  headerCopy: { flex: 1, paddingTop: 1 },
  eyebrow: { color: C.gold, fontSize: 10, fontWeight: '900', letterSpacing: 1.15 },
  title: { color: C.maroonDark, fontSize: 27, lineHeight: 33, fontWeight: '900', marginTop: 3 },
  subtitle: { color: C.muted, fontSize: 11.5, lineHeight: 18, marginTop: 3 },

  trustCard: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    padding: 13,
    borderRadius: 16,
    backgroundColor: '#F2FBF6',
    borderWidth: 1,
    borderColor: '#D0ECDD',
    marginBottom: 12,
  },
  trustIcon: {
    width: 40,
    height: 40,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E2F6EA',
  },
  trustCopy: { flex: 1 },
  trustTitle: { color: '#145B43', fontSize: 11.5, fontWeight: '900' },
  trustText: { color: '#4C7566', fontSize: 9.8, lineHeight: 15, marginTop: 2 },

  authCard: {
    padding: 15,
    borderRadius: 19,
    backgroundColor: C.paper,
    borderWidth: 1,
    borderColor: C.line,
  },
  segment: {
    flexDirection: 'row',
    backgroundColor: '#F6EEE7',
    padding: 4,
    borderRadius: 13,
    marginBottom: 17,
  },
  segmentButton: {
    flex: 1,
    minHeight: 39,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentActive: { backgroundColor: C.maroon },
  segmentText: { color: '#776A64', fontSize: 11, fontWeight: '900' },
  segmentTextActive: { color: '#FFFFFF' },
  formTitle: { color: C.text, fontSize: 18, fontWeight: '900' },
  formSubtitle: { color: C.muted, fontSize: 10.5, lineHeight: 16, marginTop: 4, marginBottom: 14 },
  fieldBlock: { marginBottom: 11 },
  label: { color: C.text, fontSize: 10.5, fontWeight: '900', marginBottom: 5 },
  input: {
    minHeight: 46,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#DED1C6',
    backgroundColor: '#FFFCF8',
    paddingHorizontal: 12,
    color: C.text,
    fontSize: 12,
  },
  twoCol: { flexDirection: 'row', gap: 9 },
  col: { flex: 1, minWidth: 0 },
  submitButton: {
    minHeight: 50,
    borderRadius: 14,
    backgroundColor: C.maroon,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 3,
  },
  disabled: { opacity: 0.55 },
  submitText: { color: '#FFFFFF', fontSize: 12.5, fontWeight: '900' },
  helperText: { color: C.muted, fontSize: 9.2, lineHeight: 14, textAlign: 'center', marginTop: 9 },

  otpNote: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 12,
    marginTop: 12,
    borderRadius: 14,
    backgroundColor: '#FFF5E8',
    borderWidth: 1,
    borderColor: '#F0D8B1',
  },
  otpText: { flex: 1, color: '#796445', fontSize: 9.8, lineHeight: 15 },
});
