import { StyleSheet } from 'react-native';

export const C = {
  bg: '#FFF8ED',
  paper: '#FFFDF9',
  maroon: '#A30D1E',
  maroonDark: '#74101B',
  gold: '#D99A2B',
  text: '#251B18',
  muted: '#776A64',
  line: '#E9D8C5',
  green: '#168458',
  blue: '#356AA0',
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: C.bg },
  listContent: { paddingHorizontal: 14, paddingTop: 10, paddingBottom: 110, flexGrow: 1 },
  header: { paddingHorizontal: 2, paddingTop: 5, paddingBottom: 13 },
  headerTop: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  headerCopy: { flex: 1 },
  addButton: {
    minHeight: 36,
    borderRadius: 11,
    paddingHorizontal: 11,
    backgroundColor: C.maroon,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  addButtonText: { color: '#FFFFFF', fontSize: 9.5, fontWeight: '900' },
  eyebrow: { color: C.gold, fontSize: 10, fontWeight: '900', letterSpacing: 1.1 },
  title: { color: C.maroonDark, fontSize: 25, lineHeight: 32, fontWeight: '900', marginTop: 3 },
  subtitle: { color: C.muted, fontSize: 11, lineHeight: 17, marginTop: 4, maxWidth: 360 },
  tabs: {
    flexDirection: 'row',
    gap: 6,
    padding: 5,
    borderRadius: 16,
    backgroundColor: '#F5EBDD',
    borderWidth: 1,
    borderColor: '#E8D9C8',
    marginBottom: 13,
  },
  tab: {
    flex: 1,
    minHeight: 43,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  activeTab: { backgroundColor: C.maroon },
  tabText: { color: C.maroon, fontSize: 10.5, fontWeight: '900' },
  activeTabText: { color: '#FFFFFF' },
  countRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 9, paddingHorizontal: 2 },
  countText: { color: C.text, fontSize: 12, fontWeight: '900' },
  countValue: {
    marginLeft: 7,
    minWidth: 22,
    height: 22,
    paddingHorizontal: 6,
    borderRadius: 11,
    overflow: 'hidden',
    backgroundColor: '#F3E5E2',
    color: C.maroon,
    textAlign: 'center',
    lineHeight: 22,
    fontSize: 9,
    fontWeight: '900',
  },
  card: {
    backgroundColor: C.paper,
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: C.line,
    marginBottom: 13,
    elevation: 2,
    shadowColor: '#5D3724',
    shadowOpacity: 0.05,
    shadowRadius: 8,
  },
  cardPressed: { opacity: 0.92, transform: [{ scale: 0.995 }] },
  banner: { width: '100%', aspectRatio: 1.85, backgroundColor: '#EEDFD3' },
  bannerPlaceholder: {
    width: '100%',
    aspectRatio: 1.85,
    alignItems: 'center',
    justifyContent: 'center',
  },
  newsPlaceholder: { backgroundColor: '#FAECEC' },
  eventPlaceholder: { backgroundColor: '#FFF4DC' },
  adPlaceholder: { backgroundColor: '#EAF7EF' },
  cardBody: { padding: 13 },
  metaRow: { flexDirection: 'row', alignItems: 'center', minHeight: 24 },
  categoryPill: { borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4 },
  newsPill: { backgroundColor: '#FCE9EC' },
  eventPill: { backgroundColor: '#FFF1D5' },
  adPill: { backgroundColor: '#EAF7EF' },
  categoryText: { fontSize: 8.5, fontWeight: '900' },
  newsText: { color: C.maroon },
  eventText: { color: '#A86600' },
  adText: { color: C.green },
  featuredPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    marginLeft: 6,
    borderRadius: 8,
    backgroundColor: C.gold,
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  featuredText: { color: '#FFFFFF', fontSize: 8, fontWeight: '900' },
  metaSpacer: { flex: 1 },
  dateText: { color: C.muted, fontSize: 8.5, fontWeight: '700' },
  cardTitle: { color: C.text, fontSize: 17, lineHeight: 23, fontWeight: '900', marginTop: 9 },
  cardExcerpt: { color: C.muted, fontSize: 10.5, lineHeight: 16, marginTop: 6 },
  cardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginTop: 11,
  },
  locationRow: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 4 },
  locationText: { flex: 1, color: C.green, fontSize: 9.5, fontWeight: '800' },
  readMoreRow: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  readMore: { color: C.maroon, fontSize: 9.5, fontWeight: '900' },
  stateCard: {
    minHeight: 260,
    marginTop: 6,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.paper,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 26,
  },
  stateTitle: {
    color: C.text,
    fontSize: 14,
    fontWeight: '900',
    textAlign: 'center',
    marginTop: 10,
  },
  stateText: { color: C.muted, fontSize: 10.5, lineHeight: 16, textAlign: 'center', marginTop: 5 },
  retryButton: {
    marginTop: 14,
    borderRadius: 11,
    backgroundColor: C.maroon,
    paddingHorizontal: 17,
    paddingVertical: 10,
  },
  retryText: { color: '#FFFFFF', fontSize: 10.5, fontWeight: '900' },
});
