import { StyleSheet } from 'react-native';

export const C = {
  bg: '#FFF8ED',
  paper: '#FFFDF9',
  maroon: '#A30D1E',
  maroonDark: '#74101B',
  gold: '#D99A2B',
  text: '#251B18',
  muted: '#776A64',
  line: '#E9D8C5',
  green: '#168458',
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: C.bg },
  content: { padding: 16, paddingBottom: 120 },
  topBar: { flexDirection: 'row', alignItems: 'center', gap: 11, marginBottom: 14 },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: C.line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  topCopy: { flex: 1 },
  eyebrow: { color: C.gold, fontSize: 9.5, fontWeight: '900', letterSpacing: 1 },
  title: { color: C.maroonDark, fontSize: 25, fontWeight: '900', marginTop: 2 },
  approvalNote: {
    flexDirection: 'row',
    gap: 9,
    borderRadius: 15,
    backgroundColor: '#EFFAF4',
    borderWidth: 1,
    borderColor: '#CDE9D9',
    padding: 12,
    marginBottom: 14,
  },
  approvalText: { flex: 1, color: '#35664F', fontSize: 10.5, lineHeight: 16, fontWeight: '700' },
  card: {
    backgroundColor: C.paper,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 18,
    padding: 14,
  },
  optionWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginBottom: 3 },
  optionChip: { borderRadius: 18, borderWidth: 1, borderColor: C.line, backgroundColor: '#FFFFFF', paddingHorizontal: 11, paddingVertical: 8 },
  optionChipActive: { backgroundColor: C.maroon, borderColor: C.maroon },
  optionText: { color: C.muted, fontSize: 9.5, fontWeight: '800' },
  optionTextActive: { color: '#FFFFFF' },
  label: { color: C.text, fontSize: 10.5, fontWeight: '900', marginTop: 12, marginBottom: 6 },
  input: {
    minHeight: 47,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    color: C.text,
    fontSize: 12,
  },
  multiline: { minHeight: 120, paddingTop: 12 },
  imagePicker: {
    overflow: 'hidden',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: '#FFF7ED',
  },
  preview: { width: '100%', aspectRatio: 1.9 },
  imagePlaceholder: { aspectRatio: 1.9, alignItems: 'center', justifyContent: 'center', gap: 7 },
  imageText: { color: C.maroon, fontSize: 10.5, fontWeight: '900' },
  submitButton: {
    marginTop: 16,
    minHeight: 50,
    borderRadius: 14,
    backgroundColor: C.maroon,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitText: { color: '#FFFFFF', fontSize: 12.5, fontWeight: '900' },
  disabled: { opacity: 0.6 },
});
