import { StyleSheet } from 'react-native';

export const C = {
  bg: '#FFF8ED',
  paper: '#FFFDF9',
  maroon: '#A30D1E',
  maroonDark: '#74101B',
  gold: '#D99A2B',
  text: '#251B18',
  muted: '#776A64',
  line: '#E9D8C5',
  green: '#168458',
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: C.bg },
  viewerOverlay: { flex: 1, backgroundColor: '#000000', alignItems: 'center', justifyContent: 'center' },
  viewerImage: { width: '100%', height: '86%' },
  viewerClose: { position: 'absolute', top: 45, right: 18, zIndex: 10, width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.16)', alignItems: 'center', justifyContent: 'center' },
  viewerCloseText: { color: '#FFFFFF', fontSize: 20, fontWeight: '800' },
  topBar: {
    height: 58,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: C.paper,
    borderBottomWidth: 1,
    borderBottomColor: C.line,
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#FFF0EC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topTitle: { color: C.maroonDark, fontSize: 16, fontWeight: '900' },
  topSpacer: { width: 38 },
  content: { padding: 14, paddingBottom: 110 },
  banner: { width: '100%', aspectRatio: 1.65, borderRadius: 18, backgroundColor: '#EEDFD3' },
  bannerPlaceholder: {
    width: '100%',
    aspectRatio: 1.65,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  newsPlaceholder: { backgroundColor: '#FAECEC' },
  eventPlaceholder: { backgroundColor: '#FFF4DC' },
  adPlaceholder: { backgroundColor: '#EAF7EF' },
  articleCard: {
    marginTop: 13,
    borderRadius: 18,
    backgroundColor: C.paper,
    borderWidth: 1,
    borderColor: C.line,
    padding: 15,
  },
  metaRow: { flexDirection: 'row', alignItems: 'center' },
  categoryPill: { borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4 },
  newsPill: { backgroundColor: '#FCE9EC' },
  eventPill: { backgroundColor: '#FFF1D5' },
  adPill: { backgroundColor: '#EAF7EF' },
  categoryText: { fontSize: 8.5, fontWeight: '900' },
  newsText: { color: C.maroon },
  eventText: { color: '#A86600' },
  adText: { color: C.green },
  featuredPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    marginLeft: 6,
    borderRadius: 8,
    backgroundColor: C.gold,
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  featuredText: { color: '#FFFFFF', fontSize: 8, fontWeight: '900' },
  title: { color: C.text, fontSize: 23, lineHeight: 31, fontWeight: '900', marginTop: 11 },
  infoStack: { gap: 8, marginTop: 14 },
  infoRow: { flexDirection: 'row', alignItems: 'center', gap: 9, paddingVertical: 4 },
  infoIconWrap: {
    width: 33,
    height: 33,
    borderRadius: 11,
    backgroundColor: '#FFF5EA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoCopy: { flex: 1 },
  infoLabel: { color: C.muted, fontSize: 8.5, fontWeight: '800' },
  infoValue: { color: C.text, fontSize: 11.5, fontWeight: '900', marginTop: 1 },
  details: { color: '#4A403B', fontSize: 13, lineHeight: 22, marginTop: 18 },
  contactCard: {
    marginTop: 13,
    borderRadius: 18,
    backgroundColor: '#FFFDF9',
    borderWidth: 1,
    borderColor: C.line,
    padding: 14,
  },
  contactTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  contactTitle: { color: C.maroonDark, fontSize: 14, fontWeight: '900' },
  contactName: { color: C.text, fontSize: 12, fontWeight: '800', marginTop: 10 },
  phoneButton: {
    marginTop: 10,
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: C.green,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  phoneButtonText: { color: '#FFFFFF', fontSize: 12, fontWeight: '900' },
  centerState: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 28 },
  stateTitle: {
    color: C.text,
    fontSize: 15,
    fontWeight: '900',
    textAlign: 'center',
    marginTop: 10,
  },
  stateText: { color: C.muted, fontSize: 10.5, lineHeight: 16, textAlign: 'center', marginTop: 5 },
  retryButton: {
    marginTop: 14,
    borderRadius: 11,
    backgroundColor: C.maroon,
    paddingHorizontal: 17,
    paddingVertical: 10,
  },
  retryText: { color: '#FFFFFF', fontSize: 10.5, fontWeight: '900' },
});
