import { StyleSheet } from 'react-native';
export const C = {
  bg: '#FFF9F1',
  paper: '#FFFDF9',
  maroon: '#A30D1E',
  maroonDark: '#7D0A16',
  gold: '#D79A25',
  text: '#211D1F',
  muted: '#6F6870',
  green: '#278255',
};
export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: C.bg },
  content: { paddingBottom: 24 },
  header: {
    padding: 14,
    gap: 8,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.paper,
  },
  brandIcon: { width: 46, height: 46, borderRadius: 12 },
  brandCopy: { flex: 1, minWidth: 0 },
  brandTitle: { color: C.maroonDark, fontSize: 20, fontWeight: '800' },
  brandSubtitle: { color: C.maroon, fontSize: 11, marginTop: 2 },
  headerIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FFF3E2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationBadge: {
    position: 'absolute',
    top: -2,
    right: -2,
    borderRadius: 12,
    minWidth: 18,
    backgroundColor: C.maroon,
    padding: 3,
    alignItems: 'center',
  },
  notificationBadgeText: { color: '#FFF', fontSize: 10, fontWeight: '700' },
  heroBannerWrap: { marginHorizontal: 14, marginTop: 10, borderRadius: 16, overflow: 'hidden' },
  heroBannerImage: { width: '100%', aspectRatio: 480 / 146 },
  matrimonyBanner: {
    margin: 14,
    marginBottom: 0,
    borderRadius: 18,
    backgroundColor: '#FBE5E3',
    overflow: 'hidden',
    flexDirection: 'row',
    minHeight: 160,
  },
  bannerCopy: { flex: 1, padding: 16, paddingRight: 8, justifyContent: 'center' },
  bannerTitle: { color: C.maroonDark, fontSize: 22, fontWeight: '800', lineHeight: 29 },
  bannerSubtitle: { color: C.muted, fontSize: 13, lineHeight: 19, marginTop: 6 },
  bannerButton: {
    backgroundColor: C.maroon,
    borderRadius: 24,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginTop: 12,
    alignSelf: 'flex-start',
  },
  bannerArtwork: { width: '38%', minHeight: 160 },
  buttonText: { color: '#FFF', fontWeight: '700', fontSize: 13, textAlign: 'center' },
  sectionHeader: {
    marginTop: 24,
    marginBottom: 12,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  sectionTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8, flex: 1, minWidth: 0 },
  sectionTitle: { color: C.maroonDark, fontSize: 20, fontWeight: '800', flexShrink: 1 },
  viewAllButton: { minHeight: 44, justifyContent: 'center' },
  viewAll: { color: C.maroon, fontSize: 12, fontWeight: '700' },
  carousel: { paddingHorizontal: 14, gap: 12, paddingBottom: 4 },
  profileCard: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#EEE2DA',
    overflow: 'hidden',
    elevation: 1,
  },
  profilePhoto: { width: '100%', aspectRatio: 1.15, backgroundColor: '#F6DFDA' },
  placeholder: { alignItems: 'center', justifyContent: 'center', gap: 8 },
  photoLabel: { color: '#76554E', fontSize: 11, textAlign: 'center', paddingHorizontal: 6 },
  profileInfo: { padding: 10, flex: 1, gap: 6 },
  profileName: { color: C.text, fontSize: 16, fontWeight: '700' },
  profileMeta: { color: C.muted, fontSize: 12, lineHeight: 18 },
  profileButton: {
    backgroundColor: C.maroon,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 4,
    marginTop: 'auto',
  },
  adsActions: {
    paddingHorizontal: 14,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
  },
  adsSubtitle: { color: C.muted, fontSize: 13, lineHeight: 19, flexGrow: 1, flexBasis: 160 },
  postAdButton: {
    borderWidth: 1,
    borderColor: C.maroon,
    borderRadius: 22,
    paddingHorizontal: 12,
    paddingVertical: 12,
    minHeight: 44,
  },
  postAdText: { color: C.maroon, fontSize: 13, fontWeight: '700' },
  adCard: {
    flexDirection: 'row',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E4E5D9',
    overflow: 'hidden',
    backgroundColor: '#FFF',
    minHeight: 158,
  },
  adImage: { width: '30%', alignSelf: 'stretch', backgroundColor: '#EAF4E9' },
  adPlaceholder: { alignItems: 'center', justifyContent: 'center' },
  adBody: { flex: 1, padding: 12, gap: 5 },
  adCategory: { color: '#28754A', fontSize: 10, fontWeight: '600' },
  adTitle: { color: C.text, fontSize: 17, fontWeight: '700' },
  adMeta: { color: C.muted, fontSize: 12, lineHeight: 18 },
  adLocation: { color: C.muted, fontSize: 11 },
  adLink: { color: C.maroon, fontSize: 12, fontWeight: '700', marginTop: 'auto' },
  emptyCard: {
    width: 270,
    minHeight: 130,
    borderRadius: 16,
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#EEE2DA',
    padding: 18,
    justifyContent: 'center',
  },
  emptyTitle: { color: C.maroon, fontSize: 15, fontWeight: '700' },
  emptyText: { color: C.muted, fontSize: 13, marginTop: 6 },
  actionGrid: { paddingHorizontal: 14, flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  actionCard: {
    width: '48%',
    flexGrow: 1,
    flexBasis: '45%',
    minHeight: 154,
    borderWidth: 1,
    borderRadius: 18,
    padding: 16,
  },
  actionTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  arrow: { fontSize: 28, color: C.maroon, fontWeight: '600' },
  actionTitle: { color: C.text, fontSize: 20, fontWeight: '700' },
  actionDescription: { color: C.muted, fontSize: 13, lineHeight: 20, marginTop: 5 },
  committeeBanner: {
    marginHorizontal: 14,
    marginTop: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#C9E1BD',
    backgroundColor: '#EFF8E9',
    minHeight: 104,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  committeeCopy: { flex: 1 },
});
