import { StyleSheet } from 'react-native';

export const C = {
  bg: '#FFF9F1',
  paper: '#FFFDF9',
  maroon: '#A30D1E',
  maroonDark: '#7D0A16',
  gold: '#D79A25',
  text: '#1F1A18',
  muted: '#6F6870',
  line: '#E8D7C3',
  green: '#0BAA67',
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: C.bg },
  content: { paddingBottom: 22 },
  header: {
    height: 72,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.paper,
    borderBottomWidth: 1,
    borderBottomColor: '#F2E6D8',
  },
  brandBadge: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: '#FFF1D7',
    overflow: 'hidden',
  },
  brandIconImage: { width: '100%', height: '100%' },
  brandCopy: { flex: 1, minWidth: 0, marginLeft: 10, marginRight: 8 },
  brandTitle: { color: C.maroonDark, fontSize: 19, fontWeight: '900', lineHeight: 24 },
  brandSubtitle: { color: C.maroon, fontSize: 9.5, fontWeight: '600', marginTop: 0 },
  headerIcon: {
    width: 37,
    height: 37,
    borderRadius: 18.5,
    backgroundColor: '#FFF7E8',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 5,
    position: 'relative',
  },
  notificationBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    borderRadius: 9,
    backgroundColor: C.maroon,
    borderWidth: 2,
    borderColor: C.paper,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationBadgeText: { color: '#FFFFFF', fontSize: 8.5, fontWeight: '900', lineHeight: 11 },
  heroBannerWrap: {
    marginHorizontal: 12,
    marginTop: 10,
    borderRadius: 15,
    overflow: 'hidden',
    backgroundColor: '#FFF4D8',
    elevation: 1,
  },
  heroBannerImage: { width: '100%', aspectRatio: 480 / 146 },
  matrimonyBannerWrap: {
    marginHorizontal: 12,
    marginTop: 7,
    borderRadius: 13,
    overflow: 'hidden',
    backgroundColor: '#FFF1F1',
    elevation: 1,
  },
  matrimonyBannerImage: { width: '100%', aspectRatio: 480 / 74 },
  quickRow: { flexDirection: 'row', gap: 5, paddingHorizontal: 12, marginTop: 7 },
  quickCard: {
    flex: 1,
    minWidth: 0,
    height: 90,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: '#E8DCCF',
    paddingHorizontal: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickIcon: { height: 30, alignItems: 'center', justifyContent: 'center', marginBottom: 4 },
  quickTitle: {
    color: C.text,
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '900',
    textAlign: 'center',
  },
  quickSub: {
    color: C.text,
    fontSize: 7.5,
    marginTop: 1.5,
    fontWeight: '700',
    textAlign: 'center',
  },
  statsStrip: {
    marginHorizontal: 12,
    marginTop: 7,
    minHeight: 64,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#EFDFC6',
    backgroundColor: '#FFF9EE',
    flexDirection: 'row',
    alignItems: 'stretch',
    paddingHorizontal: 5,
    paddingVertical: 7,
  },
  statItem: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  statIconWrap: {
    width: 29,
    height: 29,
    borderRadius: 14.5,
    backgroundColor: '#FFF0D9',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 3,
  },
  statCopy: { flexShrink: 1 },
  statValue: { color: C.maroon, fontSize: 11, fontWeight: '900', lineHeight: 13 },
  statLabel: { color: C.text, fontSize: 7.5, fontWeight: '700', lineHeight: 10, marginTop: 1 },
  statDivider: { width: 1, backgroundColor: '#EAD8BE', marginVertical: 4 },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 13,
    marginTop: 15,
    marginBottom: 7,
  },
  sectionTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  sectionTitle: { color: C.text, fontSize: 16, fontWeight: '900' },
  viewAll: { color: C.maroon, fontSize: 10.5, fontWeight: '900' },
  profileRow: { paddingHorizontal: 12, gap: 8 },
  profileCard: {
    width: 132,
    backgroundColor: '#FFFFFF',
    borderRadius: 11,
    borderWidth: 1,
    borderColor: '#ECE4DA',
    overflow: 'hidden',
    elevation: 2,
  },
  profilePhoto: { width: '100%', height: 116, backgroundColor: '#E6D7C4' },
  profilePhotoPlaceholder: { alignItems: 'center', justifyContent: 'center' },
  verified: {
    position: 'absolute',
    top: 104,
    left: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#E9FAF1',
    borderRadius: 5,
    paddingHorizontal: 5,
    paddingVertical: 2,
  },
  verifiedText: { color: C.green, fontSize: 7.5, fontWeight: '900' },
  profileInfo: { padding: 7, paddingTop: 9 },
  profileNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 3,
  },
  profileName: { color: C.text, fontSize: 11.5, fontWeight: '900', flex: 1 },
  profileMeta: { color: C.muted, fontSize: 8.5, lineHeight: 12, marginTop: 1 },
  profileEmptyCard: {
    width: 235,
    minHeight: 116,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: '#ECE4DA',
    backgroundColor: '#FFFDF9',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  profileEmptyTitle: {
    color: C.maroon,
    fontSize: 10.5,
    fontWeight: '900',
    marginTop: 7,
    textAlign: 'center',
  },
  profileEmptyText: {
    color: C.muted,
    fontSize: 8.5,
    lineHeight: 12,
    marginTop: 3,
    textAlign: 'center',
  },
  adsSectionHeader: { marginTop: 16, paddingHorizontal: 13 },
  adsHeaderTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  adsTitleRow: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 5 },
  adsTitle: { color: C.maroon, fontSize: 15, fontWeight: '900' },
  adsEnglish: {
    color: C.maroon,
    fontSize: 10.5,
    fontWeight: '800',
    fontStyle: 'italic',
    flexShrink: 1,
  },
  adsActionRow: {
    marginTop: 5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  adsSubtitle: { flex: 1, color: C.muted, fontSize: 8.5, lineHeight: 12 },
  postAdButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: C.maroon,
    borderRadius: 9,
    paddingLeft: 10,
    paddingRight: 5,
    paddingVertical: 7,
  },
  postAdButtonText: { color: '#FFF', fontSize: 9, fontWeight: '900' },
  freeBadge: {
    backgroundColor: '#16B96A',
    borderRadius: 5,
    paddingHorizontal: 5,
    paddingVertical: 2.5,
  },
  freeBadgeText: { color: '#FFF', fontSize: 7, fontWeight: '900' },
  adsRow: { paddingHorizontal: 12, paddingTop: 8, gap: 8 },
  adCard: {
    width: 205,
    height: 83,
    borderRadius: 10,
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#ECE3D7',
    flexDirection: 'row',
    overflow: 'hidden',
    elevation: 1,
  },
  adImage: { width: 77, height: '100%', backgroundColor: '#EBDCC9' },
  adImagePlaceholder: {
    width: 77,
    height: '100%',
    backgroundColor: '#EAF7EF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  adBody: { flex: 1, padding: 7 },
  adTitle: { color: C.maroon, fontSize: 10.5, fontWeight: '900' },
  adMeta: { color: C.muted, fontSize: 8, marginTop: 2 },
  adFooter: { marginTop: 'auto', flexDirection: 'row', alignItems: 'center', gap: 4 },
  tag: { backgroundColor: '#FFF0F1', borderRadius: 5, paddingHorizontal: 5, paddingVertical: 2 },
  tagText: { color: '#D1293D', fontSize: 7 },
  adCity: { color: '#637083', fontSize: 6.8, flexShrink: 1 },
  emptyAdCard: {
    width: 260,
    minHeight: 83,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#ECE3D7',
    backgroundColor: '#FFFDF9',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    paddingHorizontal: 12,
  },
  emptyAdCopy: { flex: 1 },
  emptyAdTitle: { color: C.maroon, fontSize: 10.5, fontWeight: '900' },
  emptyAdText: { color: C.muted, fontSize: 8, lineHeight: 12, marginTop: 2 },
  closingBanner: {
    marginHorizontal: 12,
    marginTop: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E9D1AE',
    backgroundColor: '#FFF6E8',
    minHeight: 76,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  closingIcon: { width: 44, alignItems: 'center' },
  closingCopy: { flex: 1, paddingHorizontal: 5 },
  closingQuote: { color: C.maroon, fontSize: 11.5, lineHeight: 16, fontWeight: '900' },
  goldLine: { width: 95, height: 1, backgroundColor: C.gold, marginTop: 7 },
  joinButton: {
    minWidth: 105,
    borderRadius: 18,
    backgroundColor: '#FFEBD5',
    paddingHorizontal: 9,
    paddingVertical: 8,
  },
  joinTitle: { color: C.maroon, fontSize: 8.5, fontWeight: '900' },
  joinSub: { color: C.maroon, fontSize: 6.7, marginTop: 1 },
});
