import { StyleSheet } from 'react-native';

export const C = {
  bg: '#FFF8ED',
  paper: '#FFFFFF',
  maroon: '#A30D1E',
  maroonDark: '#77101B',
  gold: '#D99A2B',
  text: '#2A211D',
  muted: '#736660',
  line: '#E8DCCF',
  green: '#16865C',
  red: '#B42318',
  amber: '#A76512',
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: C.bg },
  content: { padding: 16, paddingBottom: 120 },
  headerRow: { flexDirection: 'row', alignItems: 'center', gap: 11, marginBottom: 14 },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: C.line,
  },
  headerCopy: { flex: 1 },
  eyebrow: { color: C.gold, fontSize: 10, fontWeight: '900', letterSpacing: 1.1 },
  title: { color: C.maroonDark, fontSize: 24, lineHeight: 30, fontWeight: '900', marginTop: 2 },

  progressBanner: {
    flexDirection: 'row',
    gap: 10,
    padding: 13,
    borderRadius: 15,
    backgroundColor: '#F2FBF6',
    borderWidth: 1,
    borderColor: '#CFEBDD',
    marginBottom: 14,
  },
  progressIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: '#E1F6EA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressCopy: { flex: 1 },
  progressTitle: { color: '#135C43', fontSize: 12, fontWeight: '900' },
  progressText: { color: '#497063', fontSize: 10.5, lineHeight: 16, marginTop: 2 },
  lockBanner: {
    flexDirection: 'row',
    gap: 9,
    alignItems: 'center',
    padding: 12,
    borderRadius: 14,
    backgroundColor: '#FFF0EE',
    borderWidth: 1,
    borderColor: '#F1CFC8',
    marginBottom: 12,
  },
  lockText: { flex: 1, color: '#7B3D36', fontSize: 11, lineHeight: 17, fontWeight: '700' },

  section: {
    borderRadius: 18,
    backgroundColor: C.paper,
    borderWidth: 1,
    borderColor: C.line,
    padding: 14,
    marginBottom: 12,
  },
  sectionTitle: { color: C.maroonDark, fontSize: 16, fontWeight: '900' },
  sectionSubtitle: { color: C.muted, fontSize: 10.5, lineHeight: 16, marginTop: 3 },
  sectionBody: { marginTop: 12, gap: 10 },
  inlineLabel: { color: C.text, fontSize: 10.5, fontWeight: '900', marginTop: 1 },
  fieldBlock: { gap: 5 },
  fieldLabel: { color: C.text, fontSize: 10.5, fontWeight: '900' },
  required: { color: C.red },
  input: {
    minHeight: 43,
    borderWidth: 1,
    borderColor: '#DFD2C6',
    borderRadius: 12,
    backgroundColor: '#FFFCF8',
    paddingHorizontal: 12,
    color: C.text,
    fontSize: 12,
  },
  dateInput: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
  },
  dateText: { color: C.text, fontSize: 12, fontWeight: '700' },
  datePlaceholder: { color: '#A69A94', fontSize: 12 },
  multilineInput: { minHeight: 88, paddingTop: 11, textAlignVertical: 'top' },
  twoCol: { flexDirection: 'row', gap: 9 },
  col: { flex: 1, minWidth: 0 },
  choiceRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  choice: {
    paddingHorizontal: 11,
    paddingVertical: 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#E0D2C7',
    backgroundColor: '#FFFCF8',
  },
  choiceActive: { backgroundColor: C.maroon, borderColor: C.maroon },
  choiceDisabled: { opacity: 0.62 },
  choiceText: { color: '#6E615B', fontSize: 10, fontWeight: '800' },
  choiceTextActive: { color: '#FFFFFF' },

  mediaLockedCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    padding: 12,
    borderRadius: 13,
    backgroundColor: '#FFF6E8',
    borderWidth: 1,
    borderColor: '#F1D6A9',
  },
  mediaLockedText: { flex: 1, color: '#7A5C2B', fontSize: 10.5, lineHeight: 16, fontWeight: '700' },
  mediaHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  mediaCopy: { flex: 1 },
  mediaTitle: { color: C.text, fontSize: 12, fontWeight: '900' },
  mediaHint: { color: C.muted, fontSize: 9.5, marginTop: 2 },
  mediaAddButton: {
    minHeight: 36,
    paddingHorizontal: 11,
    borderRadius: 11,
    backgroundColor: C.maroon,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  mediaAddText: { color: '#FFFFFF', fontSize: 9.5, fontWeight: '900' },
  emptyMedia: {
    minHeight: 92,
    borderRadius: 13,
    backgroundColor: '#FBF7F2',
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#DFD1C4',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 14,
  },
  emptyMediaText: {
    color: C.muted,
    fontSize: 10,
    lineHeight: 15,
    textAlign: 'center',
    marginTop: 5,
  },
  photoGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 },
  photoCard: {
    width: '48%',
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E6D8CC',
    backgroundColor: '#FFFDF9',
  },
  photoImage: { width: '100%', aspectRatio: 0.86, backgroundColor: '#F2E7DE' },
  photoInfo: { padding: 8, gap: 7 },
  photoStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 5,
  },
  photoStatus: { color: C.muted, fontSize: 8.5, fontWeight: '800' },
  primaryPill: {
    color: C.green,
    fontSize: 8,
    fontWeight: '900',
    backgroundColor: '#E8F7EF',
    borderRadius: 7,
    paddingHorizontal: 6,
    paddingVertical: 3,
  },
  photoActions: {
    minHeight: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 6,
  },
  photoActionText: { color: C.maroon, fontSize: 8.5, fontWeight: '900' },
  deleteActionText: { color: C.red, fontSize: 8.5, fontWeight: '900' },
  divider: { height: 1, backgroundColor: '#EEE2D8', marginVertical: 3 },
  kundaliButton: {
    minHeight: 36,
    paddingHorizontal: 10,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: '#DDBDB6',
    backgroundColor: '#FFF8F5',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  kundaliButtonText: { color: C.maroon, fontSize: 9.5, fontWeight: '900' },
  kundaliCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    padding: 11,
    borderRadius: 13,
    backgroundColor: '#FBF7F2',
    borderWidth: 1,
    borderColor: '#E6D9CE',
  },
  kundaliIcon: {
    width: 40,
    height: 40,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF0EC',
  },
  kundaliCopy: { flex: 1 },
  kundaliName: { color: C.text, fontSize: 10.5, fontWeight: '900' },
  kundaliStatus: { color: C.muted, fontSize: 9, marginTop: 2 },
  mediaProgress: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingTop: 3,
  },
  mediaProgressText: { color: C.muted, fontSize: 9.5, fontWeight: '700' },

  actionsCard: { gap: 9, paddingTop: 4 },
  draftButton: {
    minHeight: 48,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#DDBDB6',
    backgroundColor: '#FFF8F5',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  draftButtonText: { color: C.maroon, fontSize: 12, fontWeight: '900' },
  submitButton: {
    minHeight: 50,
    borderRadius: 14,
    backgroundColor: C.maroon,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  submitButtonText: { color: '#FFFFFF', fontSize: 12, fontWeight: '900' },
  disabledButton: { opacity: 0.52 },

  centerState: { flex: 1, paddingHorizontal: 28, alignItems: 'center', justifyContent: 'center' },
  centerTitle: {
    color: C.maroonDark,
    fontSize: 20,
    fontWeight: '900',
    textAlign: 'center',
    marginTop: 14,
  },
  centerText: { color: C.muted, fontSize: 12.5, lineHeight: 20, textAlign: 'center', marginTop: 8 },
  centerButton: {
    width: '100%',
    minHeight: 48,
    marginTop: 20,
    borderRadius: 14,
    backgroundColor: C.maroon,
    alignItems: 'center',
    justifyContent: 'center',
  },
  centerButtonText: { color: '#FFFFFF', fontSize: 12.5, fontWeight: '900' },
});
