import { StyleSheet } from 'react-native';

export const C = {
  bg: '#FFF9F1',
  paper: '#FFFFFF',
  maroon: '#A30D1E',
  text: '#231C19',
  muted: '#756B66',
  line: '#E9DCCF',
  red: '#B42318',
};

export const styles = StyleSheet.create({
  flexFill: { flex: 1 },
  safeArea: { flex: 1, backgroundColor: C.bg },
  header: {
    minHeight: 68,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    borderBottomWidth: 1,
    borderBottomColor: C.line,
    backgroundColor: '#FFFDF9',
  },
  iconButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#FFF0EC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  eyebrow: { color: C.maroon, fontSize: 9, fontWeight: '900', letterSpacing: 1 },
  title: { color: C.text, fontSize: 18, fontWeight: '900' },
  content: { padding: 14, paddingBottom: 100, gap: 10 },
  card: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    padding: 10,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.paper,
  },
  photo: { width: 72, height: 84, borderRadius: 11, backgroundColor: '#EEE1D7' },
  photoPlaceholder: {
    width: 72,
    height: 84,
    borderRadius: 11,
    backgroundColor: '#F3E8DF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardBody: { flex: 1 },
  name: { color: C.text, fontSize: 14, fontWeight: '900' },
  meta: { color: C.muted, fontSize: 10, marginTop: 4 },
  removeButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#FFF1F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 28, gap: 10 },
  empty: { alignItems: 'center', paddingVertical: 60, gap: 10 },
  muted: { color: C.muted, fontSize: 11, lineHeight: 17, textAlign: 'center' },
  primary: {
    marginTop: 8,
    backgroundColor: C.maroon,
    borderRadius: 11,
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  primaryText: { color: '#FFFFFF', fontSize: 11, fontWeight: '900' },
});
