import { StyleSheet } from 'react-native';

export const C = {
  bg: '#FFF9F1',
  paper: '#FFFFFF',
  maroon: '#A30D1E',
  text: '#231C19',
  muted: '#756B66',
  line: '#E9DCCF',
  green: '#16865C',
  red: '#B42318',
  blue: '#2F62A3',
  amber: '#B76A12',
};

export const styles = StyleSheet.create({
  flexFill: { flex: 1 },
  safeArea: { flex: 1, backgroundColor: C.bg },
  header: {
    minHeight: 68,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    borderBottomWidth: 1,
    borderBottomColor: C.line,
    backgroundColor: '#FFFDF9',
  },
  iconButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#FFF0EC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  eyebrow: { color: C.maroon, fontSize: 9, fontWeight: '900', letterSpacing: 1 },
  title: { color: C.text, fontSize: 18, fontWeight: '900' },
  tabs: { flexDirection: 'row', padding: 10, gap: 8 },
  tab: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 10,
    borderRadius: 11,
    backgroundColor: '#F4ECE6',
  },
  tabActive: { backgroundColor: C.maroon },
  tabText: { color: C.muted, fontSize: 10, fontWeight: '900' },
  tabTextActive: { color: '#FFFFFF' },
  content: { padding: 14, paddingTop: 4, gap: 10, paddingBottom: 100 },
  card: {
    padding: 11,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.paper,
  },
  profileRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  photo: { width: 62, height: 72, borderRadius: 10, backgroundColor: '#EEE1D7' },
  photoPlaceholder: {
    width: 62,
    height: 72,
    borderRadius: 10,
    backgroundColor: '#F3E8DF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  name: { color: C.text, fontSize: 13, fontWeight: '900' },
  meta: { color: C.muted, fontSize: 9.5, marginTop: 3 },
  status: { paddingHorizontal: 7, paddingVertical: 4, borderRadius: 7 },
  statusText: { fontSize: 8, fontWeight: '900' },
  message: {
    color: C.text,
    fontSize: 10,
    lineHeight: 16,
    marginTop: 9,
    backgroundColor: '#FFF7EF',
    borderRadius: 9,
    padding: 8,
  },
  actions: { flexDirection: 'row', gap: 8, marginTop: 10 },
  responseButton: { flex: 1, alignItems: 'center', paddingVertical: 10, borderRadius: 10 },
  reject: { backgroundColor: '#FFF0EE', borderWidth: 1, borderColor: '#F4C9C5' },
  accept: { backgroundColor: C.green },
  rejectText: { color: C.red, fontSize: 10, fontWeight: '900' },
  acceptText: { color: '#FFFFFF', fontSize: 10, fontWeight: '900' },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 28, gap: 10 },
  empty: { alignItems: 'center', paddingVertical: 60, gap: 10 },
  primary: {
    marginTop: 8,
    backgroundColor: C.maroon,
    borderRadius: 11,
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  primaryText: { color: '#FFFFFF', fontSize: 11, fontWeight: '900' },
});
