import { StyleSheet } from 'react-native';

export const C = {
  bg: '#FFF9F1',
  paper: '#FFFFFF',
  maroon: '#A30D1E',
  maroonDark: '#7D0A16',
  gold: '#D99A2B',
  text: '#231C19',
  muted: '#756B66',
  line: '#E9DCCF',
  green: '#0BAA67',
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: C.bg },
  listContent: { paddingHorizontal: 14, paddingBottom: 24 },
  header: {
    paddingTop: 10,
    paddingBottom: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  eyebrow: { color: C.gold, fontSize: 11, fontWeight: '700', letterSpacing: 0.7 },
  title: { color: C.maroonDark, fontSize: 25, lineHeight: 31, fontWeight: '700', marginTop: 3 },
  subtitle: { color: C.muted, fontSize: 11, marginTop: 3 },
  myProfileButton: {
    minWidth: 74,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    paddingVertical: 8,
    paddingHorizontal: 7,
    borderRadius: 12,
    backgroundColor: '#FFF0EC',
    borderWidth: 1,
    borderColor: '#F0D1C8',
  },
  myProfileText: { color: C.maroon, fontSize: 11, fontWeight: '700' },

  createProfileBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 16,
    padding: 12,
    marginBottom: 12,
    backgroundColor: '#FFF1EC',
    borderWidth: 1,
    borderColor: '#F0CEC4',
  },
  createProfileIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  createProfileCopy: { flex: 1, minWidth: 0 },
  createProfileTitle: { color: C.maroonDark, fontSize: 13, fontWeight: '700' },
  createProfileText: { color: C.muted, fontSize: 12, lineHeight: 14, marginTop: 2 },
  createProfileButton: {
    minWidth: 58,
    minHeight: 44,
    borderRadius: 11,
    paddingHorizontal: 10,
    backgroundColor: C.maroon,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  createProfileButtonText: { color: '#FFFFFF', fontSize: 12, fontWeight: '700' },

  filterBlock: {
    borderRadius: 15,
    padding: 12,
    backgroundColor: '#FFFDF9',
    borderWidth: 1,
    borderColor: C.line,
    marginBottom: 9,
  },
  filterBlockCompact: { marginTop: 10, paddingTop: 10, borderTopWidth: 1, borderTopColor: C.line },
  filterLabel: { color: C.text, fontSize: 11, fontWeight: '700', marginBottom: 7 },
  genderRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  horizontalChips: { gap: 7, paddingRight: 14 },
  chip: {
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#E5D6CA',
    backgroundColor: '#FFFDF9',
  },
  chipActive: { backgroundColor: C.maroon, borderColor: C.maroon },
  chipText: { color: '#695D58', fontSize: 12, fontWeight: '800' },
  chipTextActive: { color: '#FFFFFF' },

  resultsRow: {
    marginTop: 8,
    marginBottom: 14,
    gap: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  resultsTitle: { color: C.maroonDark, fontSize: 20, fontWeight: '700', textAlign: 'center' },
  resultsCount: { color: C.muted, fontSize: 12, marginTop: 2, textAlign: 'center' },

  columns: { gap: 9 },
  card: {
    flex: 1,
    maxWidth: '48.5%',
    minWidth: 0,
    marginBottom: 10,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: C.paper,
    borderWidth: 1,
    borderColor: '#EADFD6',
    elevation: 2,
    shadowColor: '#68452D',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  photoWrap: { width: '100%', aspectRatio: 1.1, backgroundColor: '#F0E5DC' },
  photo: { width: '100%', height: '100%' },
  photoPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F6ECE3',
  },
  featuredBadge: {
    position: 'absolute',
    top: 7,
    right: 7,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    borderRadius: 7,
    backgroundColor: C.gold,
    paddingHorizontal: 6,
    paddingVertical: 3,
  },
  featuredText: { color: '#FFFFFF', fontSize: 12, fontWeight: '700' },
  cardBody: { padding: 10, gap: 7, flex: 1 },
  name: { color: C.text, fontSize: 15, fontWeight: '700' },
  detailRow: { flexDirection: 'row', gap: 5, alignItems: 'flex-start' },
  meta: { color: C.muted, fontSize: 12, lineHeight: 18, flex: 1 },
  viewProfileButton: {
    marginTop: 'auto',
    minHeight: 44,
    paddingHorizontal: 4,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: C.maroon,
    justifyContent: 'center',
  },
  viewProfileText: { color: '#FFFFFF', fontSize: 12, fontWeight: '700', textAlign: 'center' },
  pressed: { opacity: 0.8 },
  headerCopy: { flex: 1, minWidth: 0 },
  headerFloral: {
    position: 'absolute',
    width: 100,
    height: 100,
    right: -14,
    top: -20,
    opacity: 0.22,
  },
  bannerFloral: { position: 'absolute', width: 65, height: 65, right: 0, top: 0, opacity: 0.2 },
  hearts: { width: 42, height: 42 },
  resultsCopy: { flexShrink: 1, maxWidth: '76%' },
  resultRule: { height: 1, backgroundColor: '#D4AA65', flex: 1 },
  ornament: { color: C.gold, fontSize: 20 },

  emptyState: {
    minHeight: 250,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 25,
  },
  emptyTitle: {
    color: C.text,
    fontSize: 15,
    fontWeight: '700',
    marginTop: 10,
    textAlign: 'center',
  },
  emptyText: { color: C.muted, fontSize: 11, lineHeight: 17, marginTop: 5, textAlign: 'center' },
  retryButton: {
    marginTop: 12,
    borderRadius: 10,
    backgroundColor: C.maroon,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  retryText: { color: '#FFFFFF', fontSize: 12, fontWeight: '700' },

  pagination: {
    paddingTop: 12,
    paddingBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
  },
  pageButton: {
    minWidth: 78,
    alignItems: 'center',
    borderRadius: 10,
    backgroundColor: C.maroon,
    paddingVertical: 9,
    paddingHorizontal: 11,
  },
  pageButtonDisabled: { opacity: 0.35 },
  pageButtonText: { color: '#FFFFFF', fontSize: 12, fontWeight: '700' },
  pageInfo: { color: C.muted, fontSize: 12, fontWeight: '800' },
  footerSpace: { height: 18 },
});
