import { StyleSheet } from 'react-native';

export const C = {
  bg: '#FFF9F1',
  paper: '#FFFFFF',
  maroon: '#A30D1E',
  maroonDark: '#7D0A16',
  gold: '#D99A2B',
  text: '#231C19',
  muted: '#746965',
  line: '#E9DCCF',
  green: '#0BAA67',
};

export const styles = StyleSheet.create({
  flexFill: { flex: 1 },
  safeArea: { flex: 1, backgroundColor: C.bg },
  topBar: {
    height: 58,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFDF9',
    borderBottomWidth: 1,
    borderBottomColor: C.line,
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#FFF0EC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topTitle: { color: C.maroonDark, fontSize: 17, fontWeight: '900' },
  topSpacer: { width: 38 },
  content: { padding: 14, paddingBottom: 110 },

  heroCard: {
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: C.paper,
    borderWidth: 1,
    borderColor: C.line,
    elevation: 2,
  },
  heroPhoto: { width: '100%', aspectRatio: 1.04, backgroundColor: '#EADDD2' },
  heroPlaceholder: {
    width: '100%',
    aspectRatio: 1.04,
    backgroundColor: '#F3E8DF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroBody: { padding: 14 },
  badgesRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 7 },
  verifiedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: 7,
    backgroundColor: '#ECFFF5',
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  verifiedText: { color: C.green, fontSize: 8.5, fontWeight: '900' },
  featuredBadge: {
    color: '#FFFFFF',
    backgroundColor: C.gold,
    borderRadius: 7,
    overflow: 'hidden',
    paddingHorizontal: 7,
    paddingVertical: 4,
    fontSize: 8,
    fontWeight: '900',
  },
  name: { color: C.text, fontSize: 24, lineHeight: 30, fontWeight: '900' },
  location: { color: C.muted, fontSize: 11, marginTop: 4 },
  headline: { color: C.maroon, fontSize: 11, fontWeight: '800', marginTop: 5 },

  contactCard: {
    marginTop: 12,
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#F1FAF5',
    borderWidth: 1,
    borderColor: '#CDE9D9',
    gap: 10,
  },
  contactHeader: { flexDirection: 'row', alignItems: 'center', gap: 9 },
  contactTitle: { color: '#155C43', fontSize: 13, fontWeight: '900' },
  contactHint: { color: '#4D7464', fontSize: 9.5, lineHeight: 14, marginTop: 2 },
  contactDetails: { gap: 7, paddingTop: 2 },
  contactValue: { color: C.text, fontSize: 12, fontWeight: '800' },
  contactEmpty: { color: C.muted, fontSize: 10.5 },
  actionsCard: { flexDirection: 'row', gap: 9, marginTop: 11 },
  disabledAction: { opacity: 0.65 },
  ownProfileNote: {
    marginTop: 11,
    borderRadius: 12,
    backgroundColor: '#F4ECE6',
    padding: 12,
    alignItems: 'center',
  },
  ownProfileText: { color: C.muted, fontSize: 10.5, fontWeight: '800' },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(35,28,25,0.45)',
    justifyContent: 'center',
    padding: 22,
  },
  senderModal: { borderRadius: 18, backgroundColor: C.paper, padding: 16 },
  senderModalTitle: { color: C.text, fontSize: 17, fontWeight: '900' },
  senderModalText: { color: C.muted, fontSize: 10, marginTop: 4, marginBottom: 10 },
  senderOption: {
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 11,
    padding: 11,
    marginTop: 7,
  },
  senderOptionName: { color: C.text, fontSize: 12, fontWeight: '900' },
  senderOptionMeta: { color: C.muted, fontSize: 9, marginTop: 2 },
  modalCancel: { alignItems: 'center', paddingVertical: 11, marginTop: 8 },
  modalCancelText: { color: C.maroon, fontSize: 11, fontWeight: '900' },
  primaryAction: {
    flex: 1,
    minHeight: 48,
    borderRadius: 13,
    backgroundColor: C.maroon,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  primaryActionText: { color: '#FFFFFF', fontSize: 12, fontWeight: '900' },
  secondaryAction: {
    flex: 1,
    minHeight: 48,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: '#E5BFC1',
    backgroundColor: '#FFF6F5',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  secondaryActionText: { color: C.maroon, fontSize: 11, fontWeight: '900' },

  section: {
    marginTop: 12,
    borderRadius: 15,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.paper,
  },
  sectionTitle: {
    color: C.maroonDark,
    fontSize: 13,
    fontWeight: '900',
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#FFF4EC',
    borderBottomWidth: 1,
    borderBottomColor: '#F0E2D7',
  },
  sectionBody: { paddingHorizontal: 12, paddingVertical: 5 },
  infoRow: {
    minHeight: 41,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'flex-start',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#EDE5DE',
  },
  infoLabel: { width: 112, color: C.muted, fontSize: 10.5, fontWeight: '700' },
  infoValue: { flex: 1, color: C.text, fontSize: 10.5, fontWeight: '800', textAlign: 'right' },
  aboutText: { color: C.text, fontSize: 11, lineHeight: 19, paddingVertical: 8 },

  privacyNote: {
    marginTop: 13,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    borderRadius: 13,
    backgroundColor: '#EFFAF4',
    padding: 12,
  },
  privacyText: { flex: 1, color: '#49635A', fontSize: 9.5, lineHeight: 15 },

  centerState: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 28 },
  stateTitle: {
    color: C.text,
    fontSize: 16,
    fontWeight: '900',
    marginTop: 12,
    textAlign: 'center',
  },
  stateText: { color: C.muted, fontSize: 11, lineHeight: 17, marginTop: 6, textAlign: 'center' },
  retryButton: {
    marginTop: 14,
    borderRadius: 10,
    backgroundColor: C.maroon,
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  retryText: { color: '#FFFFFF', fontSize: 10, fontWeight: '900' },
});
