import { StyleSheet } from 'react-native';

export const C = {
  bg: '#FFF9F1',
  paper: '#FFFFFF',
  maroon: '#A30D1E',
  maroonDark: '#7D0A16',
  gold: '#D99A2B',
  text: '#231C19',
  muted: '#756B66',
  line: '#E9DCCF',
  green: '#0BAA67',
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: C.bg },
  listContent: { paddingHorizontal: 14, paddingBottom: 108 },
  header: {
    paddingTop: 10,
    paddingBottom: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  eyebrow: { color: C.gold, fontSize: 11, fontWeight: '900', letterSpacing: 0.7 },
  title: { color: C.maroonDark, fontSize: 25, lineHeight: 31, fontWeight: '900', marginTop: 3 },
  subtitle: { color: C.muted, fontSize: 11, marginTop: 3 },
  myProfileButton: {
    minWidth: 74,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    paddingVertical: 8,
    paddingHorizontal: 7,
    borderRadius: 12,
    backgroundColor: '#FFF0EC',
    borderWidth: 1,
    borderColor: '#F0D1C8',
  },
  myProfileText: { color: C.maroon, fontSize: 8.5, fontWeight: '900' },

  createProfileBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 16,
    padding: 12,
    marginBottom: 12,
    backgroundColor: '#FFF1EC',
    borderWidth: 1,
    borderColor: '#F0CEC4',
  },
  createProfileIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  createProfileCopy: { flex: 1, minWidth: 0 },
  createProfileTitle: { color: C.maroonDark, fontSize: 13, fontWeight: '900' },
  createProfileText: { color: C.muted, fontSize: 9.5, lineHeight: 14, marginTop: 2 },
  createProfileButton: {
    minWidth: 58,
    minHeight: 34,
    borderRadius: 11,
    paddingHorizontal: 10,
    backgroundColor: C.maroon,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  createProfileButtonText: { color: '#FFFFFF', fontSize: 10, fontWeight: '900' },

  filterBlock: {
    borderRadius: 15,
    padding: 12,
    backgroundColor: '#FFFDF9',
    borderWidth: 1,
    borderColor: C.line,
    marginBottom: 9,
  },
  filterBlockCompact: { marginTop: 2, marginBottom: 8 },
  filterLabel: { color: C.text, fontSize: 11, fontWeight: '900', marginBottom: 7 },
  genderRow: { flexDirection: 'row', gap: 7 },
  horizontalChips: { gap: 7, paddingRight: 14 },
  chip: {
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#E5D6CA',
    backgroundColor: '#FFFDF9',
  },
  chipActive: { backgroundColor: C.maroon, borderColor: C.maroon },
  chipText: { color: '#695D58', fontSize: 10, fontWeight: '800' },
  chipTextActive: { color: '#FFFFFF' },

  resultsRow: {
    marginTop: 8,
    marginBottom: 9,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  resultsTitle: { color: C.text, fontSize: 17, fontWeight: '900' },
  resultsCount: { color: C.muted, fontSize: 9.5, marginTop: 2 },

  columns: { gap: 9 },
  card: {
    flex: 1,
    minWidth: 0,
    marginBottom: 10,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: C.paper,
    borderWidth: 1,
    borderColor: '#EADFD6',
    elevation: 2,
  },
  photoWrap: { width: '100%', aspectRatio: 0.87, backgroundColor: '#F0E5DC' },
  photo: { width: '100%', height: '100%' },
  photoPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F6ECE3',
  },
  verifiedBadge: {
    position: 'absolute',
    left: 7,
    bottom: 7,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    borderRadius: 7,
    backgroundColor: '#ECFFF5',
    paddingHorizontal: 6,
    paddingVertical: 3,
  },
  verifiedText: { color: C.green, fontSize: 7.5, fontWeight: '900' },
  featuredBadge: {
    position: 'absolute',
    top: 7,
    right: 7,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    borderRadius: 7,
    backgroundColor: C.gold,
    paddingHorizontal: 6,
    paddingVertical: 3,
  },
  featuredText: { color: '#FFFFFF', fontSize: 6.8, fontWeight: '900' },
  cardBody: { padding: 9 },
  nameRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  name: { flex: 1, color: C.text, fontSize: 12.5, fontWeight: '900' },
  meta: { color: C.muted, fontSize: 9, marginTop: 3 },
  work: { color: C.maroon, fontSize: 9, fontWeight: '700', marginTop: 3 },

  emptyState: {
    minHeight: 250,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 25,
  },
  emptyTitle: {
    color: C.text,
    fontSize: 15,
    fontWeight: '900',
    marginTop: 10,
    textAlign: 'center',
  },
  emptyText: { color: C.muted, fontSize: 11, lineHeight: 17, marginTop: 5, textAlign: 'center' },
  retryButton: {
    marginTop: 12,
    borderRadius: 10,
    backgroundColor: C.maroon,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  retryText: { color: '#FFFFFF', fontSize: 10, fontWeight: '900' },

  pagination: {
    paddingTop: 12,
    paddingBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
  },
  pageButton: {
    minWidth: 78,
    alignItems: 'center',
    borderRadius: 10,
    backgroundColor: C.maroon,
    paddingVertical: 9,
    paddingHorizontal: 11,
  },
  pageButtonDisabled: { opacity: 0.35 },
  pageButtonText: { color: '#FFFFFF', fontSize: 10, fontWeight: '900' },
  pageInfo: { color: C.muted, fontSize: 10, fontWeight: '800' },
  footerSpace: { height: 18 },
});
