import { StyleSheet } from 'react-native';

export const C = {
  bg: '#FFF8ED',
  paper: '#FFFFFF',
  maroon: '#A30D1E',
  maroonDark: '#77101B',
  gold: '#D99A2B',
  text: '#2A211D',
  muted: '#736660',
  line: '#E9DDD1',
  green: '#16865C',
  amber: '#B76A12',
  red: '#B42318',
  blue: '#2F62A3',
};

export const styles = StyleSheet.create({
  flexFill: { flex: 1 },
  safeArea: { flex: 1, backgroundColor: C.bg },
  content: { padding: 16, paddingBottom: 110 },
  headerRow: { flexDirection: 'row', alignItems: 'center', gap: 11, marginBottom: 14 },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: C.line,
  },
  headerCopy: { flex: 1 },
  eyebrow: { color: C.gold, fontSize: 10, fontWeight: '900', letterSpacing: 1.1 },
  title: { color: C.maroonDark, fontSize: 23, lineHeight: 29, fontWeight: '900', marginTop: 2 },
  addButton: {
    width: 42,
    height: 42,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.maroon,
  },
  infoBanner: {
    flexDirection: 'row',
    gap: 10,
    padding: 13,
    borderRadius: 15,
    backgroundColor: '#F2FBF6',
    borderWidth: 1,
    borderColor: '#CFEBDD',
    marginBottom: 15,
  },
  infoCopy: { flex: 1 },
  infoTitle: { color: '#135C43', fontSize: 12, fontWeight: '900' },
  infoText: { color: '#497063', fontSize: 10.5, lineHeight: 16, marginTop: 2 },
  shortlistLink: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
    marginBottom: 15,
    borderRadius: 14,
    backgroundColor: '#FFFDF9',
    borderWidth: 1,
    borderColor: C.line,
  },
  shortlistIcon: {
    width: 36,
    height: 36,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF1EE',
  },
  shortlistCopy: { flex: 1 },
  shortlistTitle: { color: C.maroonDark, fontSize: 12, fontWeight: '900' },
  shortlistText: { color: C.muted, fontSize: 9.5, marginTop: 2 },
  listBlock: { gap: 10 },
  sectionHeadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  sectionTitle: { color: C.text, fontSize: 15, fontWeight: '900' },
  card: {
    padding: 14,
    borderRadius: 17,
    backgroundColor: C.paper,
    borderWidth: 1,
    borderColor: C.line,
    elevation: 2,
  },
  cardTopRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 16,
    backgroundColor: '#FFF2E8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardHeading: { flex: 1, minWidth: 0 },
  name: { color: C.text, fontSize: 16, fontWeight: '900' },
  profileFor: { color: C.muted, fontSize: 10.5, marginTop: 3 },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 6, borderRadius: 9 },
  statusText: { fontSize: 9, fontWeight: '900' },
  metaRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 12 },
  metaText: { flexShrink: 1, color: C.muted, fontSize: 10.5 },
  metaDot: { color: '#B7A69D', fontSize: 11 },
  rejectionBox: {
    marginTop: 11,
    padding: 10,
    borderRadius: 12,
    backgroundColor: '#FFF5F3',
    borderWidth: 1,
    borderColor: '#F5D4CF',
  },
  rejectionTitle: { color: C.red, fontSize: 10, fontWeight: '900' },
  rejectionText: { color: '#7C4B46', fontSize: 10.5, lineHeight: 16, marginTop: 3 },
  approvedEditNote: { marginTop: 10, padding: 9, borderRadius: 10, backgroundColor: '#F0F8F4' },
  approvedEditText: { color: '#32644F', fontSize: 9.5, fontWeight: '700' },
  cardActions: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  secondaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    minHeight: 40,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E4C8C1',
    backgroundColor: '#FFF8F5',
  },
  secondaryButtonText: { color: C.maroon, fontSize: 10.5, fontWeight: '900' },
  viewButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    minHeight: 40,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#CCE7D9',
    backgroundColor: '#F3FBF7',
  },
  viewButtonText: { color: C.green, fontSize: 10.5, fontWeight: '900' },
  primaryButton: {
    flex: 1,
    minWidth: 150,
    minHeight: 40,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: C.maroon,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  primaryButtonText: { color: '#FFFFFF', fontSize: 10.5, fontWeight: '900' },
  deleteDraftButton: {
    alignSelf: 'flex-start',
    marginTop: 10,
    minHeight: 34,
    paddingHorizontal: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#F0C8C2',
    backgroundColor: '#FFF7F5',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  deleteDraftText: { color: C.red, fontSize: 9.5, fontWeight: '900' },
  deleteRequestButton: {
    alignSelf: 'flex-start',
    marginTop: 10,
    minHeight: 36,
    paddingHorizontal: 11,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#F0C8C2',
    backgroundColor: '#FFF7F5',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  deleteRequestText: { color: C.red, fontSize: 9.5, fontWeight: '900' },
  deletePendingBox: {
    marginTop: 10,
    padding: 10,
    borderRadius: 11,
    backgroundColor: '#FFF8E8',
    borderWidth: 1,
    borderColor: '#F0D6A0',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  deletePendingTitle: { color: '#8A570D', fontSize: 10, fontWeight: '900' },
  deletePendingText: { color: '#806B4C', fontSize: 9.5, lineHeight: 14, marginTop: 2 },
  buttonDisabled: { opacity: 0.62 },
  lockedState: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  lockedText: { color: '#8B7F78', fontSize: 9.5, fontWeight: '700' },
  stateBox: { alignItems: 'center', justifyContent: 'center', paddingVertical: 52, gap: 10 },
  stateTitle: { color: C.text, fontSize: 14, fontWeight: '900', textAlign: 'center' },
  retryButton: {
    marginTop: 4,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 11,
    backgroundColor: C.maroon,
  },
  retryText: { color: '#FFFFFF', fontSize: 11, fontWeight: '900' },
  emptyCard: {
    alignItems: 'center',
    padding: 24,
    marginTop: 6,
    borderRadius: 20,
    backgroundColor: C.paper,
    borderWidth: 1,
    borderColor: C.line,
  },
  emptyIcon: {
    width: 76,
    height: 76,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF0EC',
  },
  emptyTitle: {
    color: C.maroonDark,
    fontSize: 18,
    fontWeight: '900',
    marginTop: 15,
    textAlign: 'center',
  },
  emptyText: { color: C.muted, fontSize: 12, lineHeight: 19, marginTop: 7, textAlign: 'center' },
  createButton: {
    marginTop: 18,
    minHeight: 46,
    paddingHorizontal: 18,
    borderRadius: 13,
    backgroundColor: C.maroon,
    alignItems: 'center',
    justifyContent: 'center',
  },
  createButtonText: { color: '#FFFFFF', fontSize: 12, fontWeight: '900' },
  authState: { flex: 1, paddingHorizontal: 28, alignItems: 'center', justifyContent: 'center' },
  authIcon: {
    width: 82,
    height: 82,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF0EC',
    borderWidth: 1,
    borderColor: '#F0D1C8',
  },
  authTitle: {
    color: C.maroonDark,
    fontSize: 21,
    lineHeight: 28,
    fontWeight: '900',
    textAlign: 'center',
    marginTop: 18,
  },
  authText: { color: C.muted, fontSize: 12.5, lineHeight: 20, textAlign: 'center', marginTop: 9 },
  loginButton: {
    width: '100%',
    minHeight: 48,
    marginTop: 20,
    borderRadius: 14,
    backgroundColor: C.maroon,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginButtonText: { color: '#FFFFFF', fontSize: 12.5, fontWeight: '900' },
  backLink: { color: C.maroon, fontSize: 11, fontWeight: '800', marginTop: 16 },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(25,18,16,0.52)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 22,
  },
  modalCard: {
    width: '100%',
    maxWidth: 460,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    padding: 18,
  },
  modalIcon: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: '#FFF0EE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalTitle: { color: C.maroonDark, fontSize: 19, fontWeight: '900', marginTop: 13 },
  modalText: { color: C.muted, fontSize: 11.5, lineHeight: 18, marginTop: 6 },
  reasonInput: {
    minHeight: 110,
    marginTop: 14,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 13,
    backgroundColor: '#FFFCF8',
    padding: 12,
    color: C.text,
    fontSize: 12,
    textAlignVertical: 'top',
  },
  reasonCount: { alignSelf: 'flex-end', color: '#998A82', fontSize: 9, marginTop: 4 },
  modalActions: { flexDirection: 'row', gap: 9, marginTop: 14 },
  modalCancel: {
    flex: 1,
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCancelText: { color: C.muted, fontSize: 11, fontWeight: '900' },
  modalSubmit: {
    flex: 1.35,
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: C.red,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalSubmitText: { color: '#FFFFFF', fontSize: 11, fontWeight: '900' },
});
