import { StyleSheet } from 'react-native';

export const C = {
  bg: '#FFF8ED',
  paper: '#FFFFFF',
  maroon: '#A30D1E',
  maroonDark: '#77101B',
  gold: '#D99A2B',
  text: '#2A211D',
  muted: '#736660',
  line: '#E8DCCF',
  green: '#16865C',
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: C.bg },
  content: { padding: 18, paddingBottom: 110 },
  eyebrow: { color: C.gold, fontSize: 10, fontWeight: '900', letterSpacing: 1.2 },
  title: { color: C.maroonDark, fontSize: 29, lineHeight: 35, fontWeight: '900', marginTop: 5 },
  subtitle: { color: C.muted, fontSize: 12.5, lineHeight: 19, marginTop: 5 },
  loadingCard: {
    minHeight: 100,
    marginTop: 18,
    borderRadius: 17,
    backgroundColor: C.paper,
    borderWidth: 1,
    borderColor: C.line,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  loadingText: { color: C.muted, fontSize: 10.5, fontWeight: '700' },
  accountCard: {
    marginTop: 18,
    padding: 14,
    borderRadius: 17,
    backgroundColor: C.paper,
    borderWidth: 1,
    borderColor: C.line,
  },
  accountTop: { flexDirection: 'row', alignItems: 'center', gap: 11 },
  accountIconVerified: {
    width: 54,
    height: 54,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF0EC',
  },
  accountCopy: { flex: 1 },
  accountTitle: { color: C.text, fontSize: 15, fontWeight: '900' },
  accountPhone: { color: C.muted, fontSize: 10.5, marginTop: 3 },
  statusPill: {
    borderRadius: 11,
    backgroundColor: '#EAF8F0',
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  statusText: { color: C.green, fontSize: 8.5, fontWeight: '900' },
  accountDivider: { height: 1, backgroundColor: '#EEE3D9', marginVertical: 11 },
  accountHint: { color: C.muted, fontSize: 10.5, lineHeight: 16 },
  guestCard: {
    marginTop: 18,
    padding: 16,
    borderRadius: 18,
    backgroundColor: C.paper,
    borderWidth: 1,
    borderColor: C.line,
    alignItems: 'center',
  },
  guestTitle: { color: C.maroonDark, fontSize: 16, fontWeight: '900', textAlign: 'center' },
  guestText: { color: C.muted, fontSize: 10.5, lineHeight: 16, textAlign: 'center', marginTop: 5 },
  authActions: { width: '100%', gap: 8, marginTop: 14 },
  loginButton: {
    minHeight: 46,
    borderRadius: 13,
    backgroundColor: C.maroon,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginText: { color: '#FFFFFF', fontSize: 12, fontWeight: '900' },
  registerButton: {
    minHeight: 45,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: '#DDBDB6',
    backgroundColor: '#FFF8F5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  registerText: { color: C.maroon, fontSize: 12, fontWeight: '900' },
  sectionTitle: { color: C.text, fontSize: 15, fontWeight: '900', marginTop: 22, marginBottom: 9 },
  menuCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    padding: 14,
    borderRadius: 16,
    backgroundColor: C.paper,
    borderWidth: 1,
    borderColor: C.line,
    marginBottom: 9,
  },
  menuCardMuted: {
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#F8F4EF',
    borderWidth: 1,
    borderColor: '#E9E0D8',
  },
  menuCopy: { flex: 1 },
  menuTitle: { color: C.maroonDark, fontSize: 13, fontWeight: '900' },
  menuTitleMuted: { color: '#605650', fontSize: 13, fontWeight: '900' },
  menuText: { color: C.muted, fontSize: 10, lineHeight: 15, marginTop: 3 },
  deleteRequestButton: {
    alignSelf: 'center',
    marginTop: 14,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  deleteRequestText: {
    color: '#9A5B5B',
    fontSize: 10,
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
  logoutButton: {
    minHeight: 46,
    marginTop: 18,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: '#E6C6C0',
    backgroundColor: '#FFF8F5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoutText: { color: C.maroon, fontSize: 11.5, fontWeight: '900' },
});
