import { StyleSheet } from 'react-native';

export const C = {
  bg: '#FFF8ED',
  paper: '#FFFDF9',
  maroon: '#A30D1E',
  maroonDark: '#74101B',
  gold: '#D99A2B',
  text: '#251B18',
  muted: '#776A64',
  line: '#E9D8C5',
  green: '#168458',
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: C.bg },
  topBar: {
    height: 58,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: C.paper,
    borderBottomWidth: 1,
    borderBottomColor: C.line,
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#FFF0EC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topTitle: { color: C.maroonDark, fontSize: 16, fontWeight: '900' },
  topSpacer: { width: 38 },
  content: { padding: 14, paddingBottom: 110 },
  banner: { width: '100%', aspectRatio: 1.75, borderRadius: 18, backgroundColor: '#EEDFD3' },
  bannerPlaceholder: {
    width: '100%',
    aspectRatio: 1.75,
    borderRadius: 18,
    backgroundColor: '#F7E9DF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroCard: {
    marginTop: 13,
    borderRadius: 18,
    backgroundColor: C.paper,
    borderWidth: 1,
    borderColor: C.line,
    padding: 15,
  },
  name: { color: C.text, fontSize: 23, lineHeight: 30, fontWeight: '900' },
  locationRow: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 8 },
  location: { color: C.green, fontSize: 11, fontWeight: '900' },
  details: { color: C.muted, fontSize: 11.5, lineHeight: 18, marginTop: 11 },
  sectionCard: {
    marginTop: 13,
    borderRadius: 18,
    backgroundColor: C.paper,
    borderWidth: 1,
    borderColor: C.line,
    padding: 14,
  },
  sectionTitle: { color: C.maroonDark, fontSize: 15, fontWeight: '900' },
  sectionHint: { color: C.muted, fontSize: 9.5, marginTop: 3 },
  infoRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 12 },
  infoText: { flex: 1, color: C.text, fontSize: 11, lineHeight: 17, fontWeight: '700' },
  linkText: { color: C.green, fontWeight: '900' },
  membersList: { gap: 9, marginTop: 12 },
  memberCard: {
    flexDirection: 'row',
    gap: 10,
    borderRadius: 14,
    backgroundColor: '#FFF8F1',
    borderWidth: 1,
    borderColor: '#EFE0D1',
    padding: 10,
  },
  memberPhoto: { width: 58, height: 58, borderRadius: 13, backgroundColor: '#EEDFD3' },
  memberPhotoPlaceholder: {
    width: 58,
    height: 58,
    borderRadius: 13,
    backgroundColor: '#F1E5DB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  memberCopy: { flex: 1, justifyContent: 'center' },
  memberName: { color: C.text, fontSize: 12.5, fontWeight: '900' },
  memberDesignation: { color: C.maroon, fontSize: 9.5, fontWeight: '800', marginTop: 2 },
  memberContact: { color: C.muted, fontSize: 9.5, marginTop: 4 },
  centerState: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 28 },
  stateTitle: {
    color: C.text,
    fontSize: 15,
    fontWeight: '900',
    textAlign: 'center',
    marginTop: 10,
  },
  stateText: { color: C.muted, fontSize: 10.5, lineHeight: 16, textAlign: 'center', marginTop: 5 },
  retryButton: {
    marginTop: 14,
    borderRadius: 11,
    backgroundColor: C.maroon,
    paddingHorizontal: 17,
    paddingVertical: 10,
  },
  retryText: { color: '#FFFFFF', fontSize: 10.5, fontWeight: '900' },
});
