import { StyleSheet } from 'react-native';

export const C = {
  bg: '#FFF8ED',
  paper: '#FFFDF9',
  maroon: '#A30D1E',
  maroonDark: '#74101B',
  gold: '#D99A2B',
  text: '#251B18',
  muted: '#776A64',
  line: '#E9D8C5',
  green: '#168458',
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: C.bg },
  listContent: { paddingHorizontal: 14, paddingTop: 10, paddingBottom: 110, flexGrow: 1 },
  header: { paddingHorizontal: 2, paddingTop: 5, paddingBottom: 14 },
  headerTop: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  headerCopy: { flex: 1 },
  addButton: {
    minHeight: 36,
    borderRadius: 11,
    paddingHorizontal: 11,
    backgroundColor: C.maroon,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  addButtonText: { color: '#FFFFFF', fontSize: 9.5, fontWeight: '900' },
  eyebrow: { color: C.gold, fontSize: 10, fontWeight: '900', letterSpacing: 1.1 },
  title: { color: C.maroonDark, fontSize: 28, lineHeight: 35, fontWeight: '900', marginTop: 3 },
  subtitle: { color: C.muted, fontSize: 11, lineHeight: 17, marginTop: 4, maxWidth: 370 },
  countPill: {
    alignSelf: 'flex-start',
    marginTop: 10,
    borderRadius: 10,
    backgroundColor: '#F3E5E2',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  countText: { color: C.maroon, fontSize: 9.5, fontWeight: '900' },
  card: {
    backgroundColor: C.paper,
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: C.line,
    marginBottom: 14,
    elevation: 2,
    shadowColor: '#5D3724',
    shadowOpacity: 0.05,
    shadowRadius: 8,
  },
  cardPressed: { opacity: 0.92, transform: [{ scale: 0.995 }] },
  banner: { width: '100%', aspectRatio: 1.85, backgroundColor: '#EEDFD3' },
  bannerPlaceholder: {
    width: '100%',
    aspectRatio: 1.85,
    backgroundColor: '#F7E9DF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardBody: { padding: 13 },
  cardTitle: { color: C.text, fontSize: 18, lineHeight: 24, fontWeight: '900' },
  locationRow: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 7 },
  locationText: { color: C.green, fontSize: 10.5, fontWeight: '800' },
  cardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginTop: 13,
  },
  memberMeta: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  memberMetaText: { color: C.muted, fontSize: 9.5, fontWeight: '800' },
  optionalText: { color: '#988A83', fontSize: 8.8, fontWeight: '700' },
  openRow: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  openText: { color: C.maroon, fontSize: 9.5, fontWeight: '900' },
  stateCard: {
    minHeight: 280,
    marginTop: 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.paper,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
  },
  stateTitle: {
    color: C.text,
    fontSize: 14,
    fontWeight: '900',
    textAlign: 'center',
    marginTop: 10,
  },
  stateText: { color: C.muted, fontSize: 10.5, lineHeight: 16, textAlign: 'center', marginTop: 5 },
  retryButton: {
    marginTop: 14,
    borderRadius: 11,
    backgroundColor: C.maroon,
    paddingHorizontal: 17,
    paddingVertical: 10,
  },
  retryText: { color: '#FFFFFF', fontSize: 10.5, fontWeight: '900' },
});
