'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import AdminSidebar from '@/components/admin-sidebar';
import { API_BASE_URL, clearAdminSession, getAdminToken, verifyAdminSession } from '@/lib/auth';

type Translation={language?:string;locale?:string;title?:string|null;details?:string|null;body?:string|null;description?:string|null};
type CommunityPost={id:string;category:string;status:string;title?:string|null;description?:string|null;body?:string|null;imageUrl?:string|null;bannerUrl?:string|null;eventDate?:string|null;location?:string|null;city?:string|null;state?:string|null;createdAt:string;translations?:Translation[]};
async function api(path:string,options:RequestInit={}){const token=getAdminToken();if(!token)throw new Error('SESSION_EXPIRED');const headers:Record<string,string>={authorization:`Bearer ${token}`,accept:'application/json'};if(options.body)headers['content-type']='application/json';const response=await fetch(`${API_BASE_URL}${path}`,{...options,headers:{...headers,...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(response.status===401||response.status===403)throw new Error('SESSION_EXPIRED');if(!response.ok)throw new Error(data?.message||data?.error||`Request failed (${response.status})`);return data;}
function text(post:CommunityPost,key:'title'|'body'|'description'){const hi=post.translations?.find(t=>t.language==='HI'||t.locale==='hi');const en=post.translations?.find(t=>t.language==='EN'||t.locale==='en');if(key==='title')return hi?.title||en?.title||post.title||'';return hi?.details||hi?.[key]||en?.details||en?.[key]||post[key]||'';}
function label(category:string){return category==='NEWS'?'News':category==='EVENT'?'Samaroh / Event':category==='ADVERTISEMENT'?'Advertisement':category;}
export default function CommunityModerationPage(){const router=useRouter();const searchParams=useSearchParams();const requestedFilter=searchParams.get('filter');const initialFilter=requestedFilter==='NEWS'||requestedFilter==='EVENT'||requestedFilter==='ADVERTISEMENT'?requestedFilter:'ALL';const[items,setItems]=useState<CommunityPost[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState<string|null>(null);const[filter,setFilter]=useState<'ALL'|'NEWS'|'EVENT'|'ADVERTISEMENT'>(initialFilter);useEffect(()=>{const f=searchParams.get('filter');setFilter(f==='NEWS'||f==='EVENT'||f==='ADVERTISEMENT'?f:'ALL');},[searchParams]);const load=useCallback(async()=>{setLoading(true);setError(null);try{const admin=await verifyAdminSession();if(!admin){router.replace('/login');return;}const data=await api('/admin/posts?status=PENDING&page=1&limit=50');setItems(data.items||[]);}catch(e){if(e instanceof Error&&e.message==='SESSION_EXPIRED'){clearAdminSession();router.replace('/login');return;}setError(e instanceof Error?e.message:'Community queue load failed');}finally{setLoading(false);}},[router]);useEffect(()=>{void load();},[load]);const visible=useMemo(()=>filter==='ALL'?items:items.filter(x=>x.category===filter),[items,filter]);const counts=useMemo(()=>({NEWS:items.filter(x=>x.category==='NEWS').length,EVENT:items.filter(x=>x.category==='EVENT').length,ADVERTISEMENT:items.filter(x=>x.category==='ADVERTISEMENT').length}),[items]);async function action(path:string,body?:unknown){setBusy(path);setError(null);try{await api(path,{method:'POST',body:body?JSON.stringify(body):undefined});await load();}catch(e){setError(e instanceof Error?e.message:'Action failed');}finally{setBusy(null);}}function reject(id:string){const reason=window.prompt('Reject करने का कारण लिखें:');if(reason?.trim())void action(`/admin/posts/${id}/reject`,{reason:reason.trim()});}
return <div className="admin-shell"><AdminSidebar/><main className="main moderation-page"><div className="moderation-top"><div><Link href="/" className="back-link">← Dashboard</Link><p className="eyebrow">COMMUNITY MODERATION</p><h1>Community Approval Center</h1><p className="subtitle">News, Samaroh और advertisements publish होने से पहले review करें।</p></div><button className="small-btn" onClick={()=>void load()}>Refresh</button></div><div className="moderation-tabs"><button className={filter==='ALL'?'active':''} onClick={()=>setFilter('ALL')}>All <b>{items.length}</b></button><button className={filter==='NEWS'?'active':''} onClick={()=>setFilter('NEWS')}>News <b>{counts.NEWS}</b></button><button className={filter==='EVENT'?'active':''} onClick={()=>setFilter('EVENT')}>Samaroh <b>{counts.EVENT}</b></button><button className={filter==='ADVERTISEMENT'?'active':''} onClick={()=>setFilter('ADVERTISEMENT')}>Ads <b>{counts.ADVERTISEMENT}</b></button></div>{error?<div className="moderation-error">{error}</div>:null}{loading?<div className="empty-state">Community queue load हो रही है…</div>:<section className="moderation-list">{visible.length===0?<div className="empty-state">इस category में कोई pending submission नहीं है।</div>:visible.map(post=>{const title=text(post,'title')||'Untitled community submission';const description=text(post,'description')||text(post,'body');const image=post.imageUrl||post.bannerUrl;return <article className="moderation-card" key={post.id}><div className="profile-summary">{image?<div className="profile-photo"><img src={image} alt=""/></div>:<div className="profile-photo"><span>{post.category?.[0]||'C'}</span></div>}<div><span className="danger-label" style={{color:'#765414',background:'#fff7e5'}}>{label(post.category)}</span><h2 style={{marginTop:8}}>{title}</h2>{description?<p>{description.length>180?`${description.slice(0,180)}…`:description}</p>:null}<small>{[post.city,post.state,post.location].filter(Boolean).join(', ')||'Location not provided'} • Submitted {new Date(post.createdAt).toLocaleDateString('en-IN')}</small></div></div><div className="moderation-actions"><button disabled={!!busy} className="reject-action" onClick={()=>reject(post.id)}>Reject</button><button disabled={!!busy} className="approve-action" onClick={()=>window.confirm(`“${title}” publish करें?`)&&void action(`/admin/posts/${post.id}/approve`)}>Approve</button></div></article>})}</section>}</main></div>}
