import { promisify } from 'node:util';
import { randomBytes, scrypt } from 'node:crypto';
import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { z } from 'zod';
import { prisma } from '../../../lib/prisma.js';
const scryptAsync=promisify(scrypt);
const listQuerySchema=z.object({search:z.string().trim().max(100).optional(),status:z.enum(['ALL','ACTIVE','BLOCKED']).default('ALL'),role:z.enum(['ALL','MEMBER','ADMIN','SUPER_ADMIN']).default('ALL'),page:z.coerce.number().int().min(1).default(1),limit:z.coerce.number().int().min(1).max(100).default(25)});
const roleSchema=z.object({role:z.enum(['MEMBER','ADMIN'])});
const createMemberSchema=z.object({phone:z.string().regex(/^\+?[1-9]\d{7,14}$/),firstName:z.string().trim().min(1).max(80),lastName:z.string().trim().min(1).max(80),email:z.string().trim().email().max(320).optional().nullable()});
async function hashPassword(password:string){const salt=randomBytes(16).toString('hex');const derived=(await scryptAsync(password,salt,64)) as Buffer;return `scrypt$${salt}$${derived.toString('hex')}`;}
function temporaryPassword(){return `Dp@${randomBytes(6).toString('base64url')}7`;}
async function requireAdmin(request:FastifyRequest,reply:FastifyReply){try{const payload=await request.jwtVerify<{sub:string}>();const user=await prisma.user.findFirst({where:{id:payload.sub,role:{in:['ADMIN','SUPER_ADMIN']},isActive:true,deletedAt:null},select:{id:true,role:true}});if(!user){await reply.code(403).send({error:'ADMIN_REQUIRED'});return null;}return user;}catch{await reply.code(401).send({error:'UNAUTHORIZED'});return null;}}
async function requireSuperAdmin(request:FastifyRequest,reply:FastifyReply){const user=await requireAdmin(request,reply);if(!user)return null;if(user.role!=='SUPER_ADMIN'){await reply.code(403).send({error:'SUPER_ADMIN_REQUIRED'});return null;}return user;}
const selectUser={id:true,phone:true,email:true,firstName:true,lastName:true,preferredLanguage:true,role:true,isPhoneVerified:true,isActive:true,lastLoginAt:true,createdAt:true,deletedAt:true,_count:{select:{matrimonyProfiles:true,communityPosts:true,committees:true,reports:true}}} as const;
export async function adminUserRoutes(app:FastifyInstance){
app.post('/',async(request,reply)=>{const admin=await requireAdmin(request,reply);if(!admin)return;const parsed=createMemberSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'VALIDATION_ERROR',fields:parsed.error.flatten().fieldErrors});const existing=await prisma.user.findUnique({where:{phone:parsed.data.phone},select:{id:true}});if(existing)return reply.code(409).send({error:'ACCOUNT_EXISTS',message:'An account already exists for this mobile number.'});const password=temporaryPassword();const passwordHash=await hashPassword(password);const user=await prisma.$transaction(async tx=>{const created=await tx.user.create({data:{phone:parsed.data.phone,firstName:parsed.data.firstName,lastName:parsed.data.lastName,email:parsed.data.email??null,role:'MEMBER',isPhoneVerified:false,isActive:true},select:selectUser});await tx.$executeRaw`INSERT INTO "UserCredential" ("userId", "passwordHash", "updatedAt") VALUES (${created.id}, ${passwordHash}, CURRENT_TIMESTAMP)`;await tx.auditLog.create({data:{actorUserId:admin.id,action:'MEMBER_ACCOUNT_ADMIN_CREATED',entityType:'User',entityId:created.id,metadata:{source:'ADMIN_ASSISTED'}}});return created;});return reply.code(201).send({user,temporaryPassword:password,message:'Share this temporary password securely. The member should change it after first login.'});});
app.get('/',async(request,reply)=>{const admin=await requireAdmin(request,reply);if(!admin)return;const parsed=listQuerySchema.safeParse(request.query);if(!parsed.success)return reply.code(400).send({error:'VALIDATION_ERROR',fields:parsed.error.flatten().fieldErrors});const{search,status,role,page,limit}=parsed.data;const where:any={deletedAt:null};if(status==='ACTIVE')where.isActive=true;if(status==='BLOCKED')where.isActive=false;if(role!=='ALL')where.role=role;if(search)where.OR=[{firstName:{contains:search,mode:'insensitive'}},{lastName:{contains:search,mode:'insensitive'}},{phone:{contains:search}},{email:{contains:search,mode:'insensitive'}}];const[items,total]=await Promise.all([prisma.user.findMany({where,select:selectUser,orderBy:{createdAt:'desc'},skip:(page-1)*limit,take:limit}),prisma.user.count({where})]);return reply.send({items,pagination:{page,limit,total,totalPages:Math.ceil(total/limit)}});});
app.get('/:id',async(request,reply)=>{const admin=await requireAdmin(request,reply);if(!admin)return;const{id}=request.params as{id:string};const user=await prisma.user.findFirst({where:{id,deletedAt:null},select:selectUser});if(!user)return reply.code(404).send({error:'USER_NOT_FOUND'});return reply.send({user});});
app.post('/:id/block',async(request,reply)=>{const admin=await requireAdmin(request,reply);if(!admin)return;const{id}=request.params as{id:string};if(id===admin.id)return reply.code(409).send({error:'CANNOT_BLOCK_SELF'});const target=await prisma.user.findFirst({where:{id,deletedAt:null},select:{id:true,role:true}});if(!target)return reply.code(404).send({error:'USER_NOT_FOUND'});if(target.role!=='MEMBER')return reply.code(403).send({error:'ADMIN_ACCOUNT_PROTECTED'});const user=await prisma.$transaction(async tx=>{const updated=await tx.user.update({where:{id},data:{isActive:false},select:selectUser});await tx.auditLog.create({data:{actorUserId:admin.id,action:'USER_BLOCKED',entityType:'User',entityId:id}});return updated;});return reply.send({user});});
app.post('/:id/unblock',async(request,reply)=>{const admin=await requireAdmin(request,reply);if(!admin)return;const{id}=request.params as{id:string};const target=await prisma.user.findFirst({where:{id,deletedAt:null},select:{id:true,role:true}});if(!target)return reply.code(404).send({error:'USER_NOT_FOUND'});if(target.role!=='MEMBER')return reply.code(403).send({error:'ADMIN_ACCOUNT_PROTECTED'});const user=await prisma.$transaction(async tx=>{const updated=await tx.user.update({where:{id},data:{isActive:true},select:selectUser});await tx.auditLog.create({data:{actorUserId:admin.id,action:'USER_UNBLOCKED',entityType:'User',entityId:id}});return updated;});return reply.send({user});});
app.post('/:id/role',async(request,reply)=>{const admin=await requireSuperAdmin(request,reply);if(!admin)return;const{id}=request.params as{id:string};if(id===admin.id)return reply.code(409).send({error:'CANNOT_CHANGE_OWN_ROLE'});const parsed=roleSchema.safeParse(request.body??{});if(!parsed.success)return reply.code(400).send({error:'VALIDATION_ERROR',fields:parsed.error.flatten().fieldErrors});const target=await prisma.user.findFirst({where:{id,deletedAt:null},select:{id:true,role:true,isActive:true}});if(!target)return reply.code(404).send({error:'USER_NOT_FOUND'});if(target.role==='SUPER_ADMIN')return reply.code(403).send({error:'SUPER_ADMIN_ACCOUNT_PROTECTED'});if(!target.isActive)return reply.code(409).send({error:'USER_MUST_BE_ACTIVE'});const user=await prisma.$transaction(async tx=>{const updated=await tx.user.update({where:{id},data:{role:parsed.data.role},select:selectUser});await tx.auditLog.create({data:{actorUserId:admin.id,action:'USER_ROLE_CHANGED',entityType:'User',entityId:id,metadata:{from:target.role,to:parsed.data.role}}});return updated;});return reply.send({user});});
}
