import type { FastifyInstance,FastifyReply,FastifyRequest } from 'fastify';import{z}from'zod';import{prisma}from'../../../lib/prisma.js';import{createCommitteeSchema,updateCommitteeSchema}from'../../committees/schemas.js';
const listQuerySchema=z.object({status:z.enum(['PENDING','PUBLISHED','REJECTED','ARCHIVED']).default('PENDING')});const rejectSchema=z.object({reason:z.string().trim().min(3).max(1000)});async function requireAdmin(request:FastifyRequest,reply:FastifyReply){try{const p=await request.jwtVerify<{sub:string}>();const u=await prisma.user.findFirst({where:{id:p.sub,role:{in:['ADMIN','SUPER_ADMIN']},isActive:true,deletedAt:null},select:{id:true,role:true}});if(!u){await reply.code(403).send({error:'ADMIN_REQUIRED'});return null;}return u;}catch{await reply.code(401).send({error:'UNAUTHORIZED'});return null;}}
const include={translations:true,members:{orderBy:[{sortOrder:'asc' as const},{createdAt:'asc' as const}]}};
export async function adminCommitteeRoutes(app:FastifyInstance){
app.get('/',async(request,reply)=>{const a=await requireAdmin(request,reply);if(!a)return;const p=listQuerySchema.safeParse(request.query);if(!p.success)return reply.code(400).send({error:'VALIDATION_ERROR',fields:p.error.flatten().fieldErrors});const items=await prisma.committee.findMany({where:{status:p.data.status,deletedAt:null},include,orderBy:[{updatedAt:'desc'},{createdAt:'desc'}]});return reply.send({items});});
app.get('/:id',async(request,reply)=>{const a=await requireAdmin(request,reply);if(!a)return;const{id}=request.params as{id:string};const committee=await prisma.committee.findFirst({where:{id,deletedAt:null},include});if(!committee)return reply.code(404).send({error:'COMMITTEE_NOT_FOUND'});return reply.send({committee});});
app.post('/',async(request,reply)=>{const a=await requireAdmin(request,reply);if(!a)return;const p=createCommitteeSchema.safeParse(request.body);if(!p.success)return reply.code(400).send({error:'VALIDATION_ERROR',fields:p.error.flatten().fieldErrors});const{translations,members,...data}=p.data;const committee=await prisma.$transaction(async tx=>{const c=await tx.committee.create({data:{...data,createdById:a.id,status:'PENDING',publishedAt:null,rejectionReason:null,translations:{create:translations},members:{create:members}},include});await tx.auditLog.create({data:{actorUserId:a.id,action:'COMMITTEE_CREATED_PENDING',entityType:'Committee',entityId:c.id}});return c;});return reply.code(201).send({committee});});
app.post('/:id/approve',async(request,reply)=>{const a=await requireAdmin(request,reply);if(!a)return;const{id}=request.params as{id:string};const e=await prisma.committee.findFirst({where:{id,deletedAt:null},select:{status:true,createdById:true}});if(!e)return reply.code(404).send({error:'COMMITTEE_NOT_FOUND'});if(e.status!=='PENDING')return reply.code(409).send({error:'COMMITTEE_NOT_PENDING',status:e.status});const committee=await prisma.$transaction(async tx=>{const c=await tx.committee.update({where:{id},data:{status:'PUBLISHED',publishedAt:new Date(),rejectionReason:null,isActive:true},include});await tx.auditLog.create({data:{actorUserId:a.id,action:'COMMITTEE_APPROVED',entityType:'Committee',entityId:id}});return c;});return reply.send({committee});});
app.post('/:id/reject',async(request,reply)=>{const a=await requireAdmin(request,reply);if(!a)return;const{id}=request.params as{id:string};const p=rejectSchema.safeParse(request.body);if(!p.success)return reply.code(400).send({error:'VALIDATION_ERROR',fields:p.error.flatten().fieldErrors});const e=await prisma.committee.findFirst({where:{id,deletedAt:null},select:{status:true}});if(!e)return reply.code(404).send({error:'COMMITTEE_NOT_FOUND'});if(e.status!=='PENDING')return reply.code(409).send({error:'COMMITTEE_NOT_PENDING',status:e.status});const committee=await prisma.$transaction(async tx=>{const c=await tx.committee.update({where:{id},data:{status:'REJECTED',rejectionReason:p.data.reason,publishedAt:null},include});await tx.auditLog.create({data:{actorUserId:a.id,action:'COMMITTEE_REJECTED',entityType:'Committee',entityId:id,metadata:{reason:p.data.reason}}});return c;});return reply.send({committee});});
app.post('/:id/deactivate',async(request,reply)=>{const a=await requireAdmin(request,reply);if(!a)return;const{id}=request.params as{id:string};const e=await prisma.committee.findFirst({where:{id,deletedAt:null},select:{status:true}});if(!e)return reply.code(404).send({error:'COMMITTEE_NOT_FOUND'});if(e.status!=='PUBLISHED')return reply.code(409).send({error:'COMMITTEE_NOT_PUBLISHED',status:e.status});const committee=await prisma.$transaction(async tx=>{const c=await tx.committee.update({where:{id},data:{status:'ARCHIVED',isActive:false},include});await tx.auditLog.create({data:{actorUserId:a.id,action:'COMMITTEE_DEACTIVATED',entityType:'Committee',entityId:id}});return c;});return reply.send({committee});});
app.post('/:id/reactivate',async(request,reply)=>{const a=await requireAdmin(request,reply);if(!a)return;const{id}=request.params as{id:string};const e=await prisma.committee.findFirst({where:{id,deletedAt:null},select:{status:true}});if(!e)return reply.code(404).send({error:'COMMITTEE_NOT_FOUND'});if(e.status!=='ARCHIVED')return reply.code(409).send({error:'COMMITTEE_NOT_ARCHIVED',status:e.status});const committee=await prisma.$transaction(async tx=>{const c=await tx.committee.update({where:{id},data:{status:'PUBLISHED',isActive:true,publishedAt:new Date()},include});await tx.auditLog.create({data:{actorUserId:a.id,action:'COMMITTEE_REACTIVATED',entityType:'Committee',entityId:id}});return c;});return reply.send({committee});});
app.patch('/:id',async(request,reply)=>{const a=await requireAdmin(request,reply);if(!a)return;const{id}=request.params as{id:string};const p=updateCommitteeSchema.safeParse(request.body);if(!p.success)return reply.code(400).send({error:'VALIDATION_ERROR',fields:p.error.flatten().fieldErrors});const e=await prisma.committee.findFirst({where:{id,deletedAt:null},select:{id:true}});if(!e)return reply.code(404).send({error:'COMMITTEE_NOT_FOUND'});const{translations,members,...data}=p.data;const committee=await prisma.$transaction(async tx=>{if(translations)await tx.committeeTranslation.deleteMany({where:{committeeId:id}});if(members)await tx.committeeMember.deleteMany({where:{committeeId:id}});const c=await tx.committee.update({where:{id},data:{...data,...(translations?{translations:{create:translations}}:{}),...(members?{members:{create:members}}:{})},include});await tx.auditLog.create({data:{actorUserId:a.id,action:'COMMITTEE_UPDATED',entityType:'Committee',entityId:id}});return c;});return reply.send({committee});});
app.delete('/:id',async(request,reply)=>{const a=await requireAdmin(request,reply);if(!a)return;const{id}=request.params as{id:string};const e=await prisma.committee.findFirst({where:{id,deletedAt:null},select:{id:true}});if(!e)return reply.code(404).send({error:'COMMITTEE_NOT_FOUND'});await prisma.$transaction(async tx=>{await tx.committee.update({where:{id},data:{deletedAt:new Date(),isActive:false,status:'ARCHIVED'}});await tx.auditLog.create({data:{actorUserId:a.id,action:'COMMITTEE_DELETED',entityType:'Committee',entityId:id}});});return reply.code(204).send();});
}
