import { promisify } from 'node:util';
import { randomBytes, scrypt, timingSafeEqual } from 'node:crypto';
import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { env } from '../../config/env.js';
import { prisma } from '../../lib/prisma.js';

import { verifyAccessToken } from './msg91.js';
const scryptAsync = promisify(scrypt);
const phoneSchema = z.object({ phone: z.string().regex(/^\+?[1-9]\d{7,14}$/, 'Use a valid phone number with country code') });
const passwordSchema = z.string().min(8, 'Password must be at least 8 characters').max(128, 'Password is too long').refine((value) => /[A-Za-z]/.test(value) && /\d/.test(value), { message: 'Password must contain at least one letter and one number' });
const registerSchema = phoneSchema.extend({ firstName: z.string().trim().min(1).max(80), lastName: z.string().trim().min(1).max(80), email: z.string().trim().email().max(320).optional().nullable(), password: passwordSchema, otpAccessToken: z.string().min(20).max(10000).optional() });
const loginSchema = phoneSchema.extend({ password: z.string().min(1).max(128) });
const changePasswordSchema=z.object({currentPassword:z.string().min(1).max(128),newPassword:passwordSchema});
const verifySchema = phoneSchema.extend({ otp: z.string().regex(/^\d{4,6}$/, 'OTP must contain 4 to 6 digits') });
const devLoginSchema = phoneSchema.extend({ firstName: z.string().trim().min(1).max(80).optional(), lastName: z.string().trim().min(1).max(80).optional(), role: z.enum(['MEMBER', 'ADMIN']).default('MEMBER') });
const adminSetupSchema = phoneSchema.extend({ setupSecret: z.string().min(1), password: passwordSchema });
const otpVerifySchema = phoneSchema.extend({ accessToken: z.string().min(20).max(10000) });
type CredentialRow = { passwordHash: string };
function normalizePhone(phone: string) { return phone.trim(); }
function phoneCandidates(phone: string) { const value = normalizePhone(phone); const digits = value.replace(/\D/g, ''); const local = digits.length === 12 && digits.startsWith('91') ? digits.slice(2) : digits; return Array.from(new Set([value, digits, local, local.length === 10 ? `+91${local}` : '', local.length === 10 ? `91${local}` : ''].filter(Boolean))); }
function secretMatches(received: string, expected: string | undefined) { if (!expected) return false; const a = Buffer.from(received); const b = Buffer.from(expected); return a.length === b.length && timingSafeEqual(a, b); }
async function hashPassword(password: string) { const salt = randomBytes(16).toString('hex'); const derivedKey = (await scryptAsync(password, salt, 64)) as Buffer; return `scrypt$${salt}$${derivedKey.toString('hex')}`; }
async function verifyPassword(password: string, stored: string) { const [algorithm, salt, hashHex] = stored.split('$'); if (algorithm !== 'scrypt' || !salt || !hashHex) return false; const storedBuffer = Buffer.from(hashHex, 'hex'); if (!storedBuffer.length) return false; const derivedKey = (await scryptAsync(password, salt, storedBuffer.length)) as Buffer; if (derivedKey.length !== storedBuffer.length) return false; return timingSafeEqual(derivedKey, storedBuffer); }
async function getCredential(userId: string) { const rows = await prisma.$queryRaw<CredentialRow[]>`SELECT "passwordHash" FROM "UserCredential" WHERE "userId" = ${userId} LIMIT 1`; return rows[0] ?? null; }
function userSelect() { return { id: true, phone: true, email: true, firstName: true, lastName: true, preferredLanguage: true, role: true, isPhoneVerified: true } as const; }
export async function authRoutes(app: FastifyInstance) {

app.post('/register', async (request, reply) => { const parsed = registerSchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: 'INVALID_REGISTRATION', message: parsed.error.issues[0]?.message ?? 'Invalid registration details', fields: parsed.error.flatten().fieldErrors }); const phone = normalizePhone(parsed.data.phone); const passwordHash = await hashPassword(parsed.data.password); const existing = await prisma.user.findUnique({ where: { phone }, select: { id: true, deletedAt: true, googleSub: true } }); if (existing) { if (existing.googleSub) return reply.code(409).send({ error: 'ACCOUNT_EXISTS', message: 'Sign in with Google or link your account.' }); const credential = await getCredential(existing.id); if (credential) return reply.code(409).send({ error: 'ACCOUNT_EXISTS', message: 'An account already exists for this mobile number.' }); if (existing.deletedAt) return reply.code(409).send({ error: 'ACCOUNT_UNAVAILABLE', message: 'This account is not available for registration.' }); } const user = await prisma.$transaction(async (tx) => { const account = existing ? await tx.user.update({ where: { id: existing.id }, data: { firstName: parsed.data.firstName, lastName: parsed.data.lastName, email: parsed.data.email ?? null, isActive: true, lastLoginAt: new Date() }, select: userSelect() }) : await tx.user.create({ data: { phone, firstName: parsed.data.firstName, lastName: parsed.data.lastName, email: parsed.data.email ?? null, role: 'MEMBER', isPhoneVerified: false, isActive: true, lastLoginAt: new Date() }, select: userSelect() }); await tx.$executeRaw`INSERT INTO "UserCredential" ("userId", "passwordHash", "updatedAt") VALUES (${account.id}, ${passwordHash}, CURRENT_TIMESTAMP)`; return account; }); if (!user.isPhoneVerified) return reply.code(201).send({ requiresPhoneVerification: true, user }); const accessToken = await reply.jwtSign({ sub: user.id, role: user.role }, { expiresIn: '7d' }); return reply.code(201).send({ accessToken, tokenType: 'Bearer', expiresIn: '7d', user }); });
app.post('/login', async (request, reply) => { const parsed = loginSchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: 'INVALID_LOGIN', message: parsed.error.issues[0]?.message ?? 'Invalid login request' }); const user = await prisma.user.findFirst({ where: { phone: { in: phoneCandidates(parsed.data.phone) }, isActive: true, deletedAt: null }, select: userSelect() }); if (!user) return reply.code(401).send({ error: 'INVALID_CREDENTIALS', message: 'Mobile number or password is incorrect.' }); const credential = await getCredential(user.id); const valid = credential ? await verifyPassword(parsed.data.password, credential.passwordHash) : false; if (!valid) return reply.code(401).send({ error: 'INVALID_CREDENTIALS', message: 'Mobile number or password is incorrect.' }); await prisma.user.update({ where: { id: user.id }, data: { lastLoginAt: new Date() } }); if (!user.isPhoneVerified) return { requiresPhoneVerification: true, user }; const accessToken = await reply.jwtSign({ sub: user.id, role: user.role }, { expiresIn: '7d' }); return { accessToken, tokenType: 'Bearer', expiresIn: '7d', user }; });
app.post('/change-password',async(request,reply)=>{try{const payload=await request.jwtVerify<{sub:string}>();const parsed=changePasswordSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'INVALID_PASSWORD',message:parsed.error.issues[0]?.message??'Invalid password'});const user=await prisma.user.findFirst({where:{id:payload.sub,isActive:true,deletedAt:null},select:{id:true}});if(!user)return reply.code(401).send({error:'UNAUTHORIZED'});const credential=await getCredential(user.id);if(!credential||!await verifyPassword(parsed.data.currentPassword,credential.passwordHash))return reply.code(400).send({error:'CURRENT_PASSWORD_INCORRECT',message:'Current password is incorrect.'});const passwordHash=await hashPassword(parsed.data.newPassword);await prisma.$executeRaw`UPDATE "UserCredential" SET "passwordHash" = ${passwordHash}, "updatedAt" = CURRENT_TIMESTAMP WHERE "userId" = ${user.id}`;return reply.send({success:true,message:'Password changed successfully.'});}catch{return reply.code(401).send({error:'UNAUTHORIZED',message:'A valid access token is required.'});}});
app.post('/admin/setup-password', async (request, reply) => { const parsed = adminSetupSchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: 'INVALID_ADMIN_SETUP', message: parsed.error.issues[0]?.message ?? 'Invalid setup request' }); if (!secretMatches(parsed.data.setupSecret, env.ADMIN_SETUP_SECRET)) return reply.code(403).send({ error: 'ADMIN_SETUP_FORBIDDEN', message: 'The setup code is invalid or admin setup is disabled.' }); const user = await prisma.user.findFirst({ where: { phone: { in: phoneCandidates(parsed.data.phone) }, role: { in: ['ADMIN', 'SUPER_ADMIN'] }, isActive: true, deletedAt: null }, select: userSelect() }); if (!user) return reply.code(404).send({ error: 'ADMIN_NOT_FOUND', message: 'No active admin account was found for this mobile number.' }); const passwordHash = await hashPassword(parsed.data.password); const existingCredential = await getCredential(user.id); if (existingCredential) await prisma.$executeRaw`UPDATE "UserCredential" SET "passwordHash" = ${passwordHash}, "updatedAt" = CURRENT_TIMESTAMP WHERE "userId" = ${user.id}`; else await prisma.$executeRaw`INSERT INTO "UserCredential" ("userId", "passwordHash", "updatedAt") VALUES (${user.id}, ${passwordHash}, CURRENT_TIMESTAMP)`; return { success: true, message: 'Admin password updated. Remove ADMIN_SETUP_SECRET from the server environment now.' }; });
app.post('/otp/send', async (request, reply) => { const parsed = phoneSchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: 'INVALID_PHONE', message: parsed.error.issues[0]?.message ?? 'Invalid phone number' }); if (env.OTP_PROVIDER !== 'msg91') return reply.code(503).send({ error: 'OTP_PROVIDER_NOT_CONFIGURED' }); const phone = normalizePhone(parsed.data.phone); const user = await prisma.user.findFirst({ where: { phone: { in: phoneCandidates(phone) }, isActive: true, deletedAt: null }, select: { id: true } }); if (!user) return reply.code(404).send({ error: 'ACCOUNT_NOT_FOUND', message: 'No account was found for this mobile number.' }); return { success: true, widgetId: env.MSG91_WIDGET_ID, otpLength: env.OTP_LENGTH, resendSeconds: env.OTP_RESEND_SECONDS, otpExpiryMinutes: env.OTP_EXPIRY_MINUTES }; });
app.post('/otp/verify', async (request, reply) => { const parsed = otpVerifySchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: 'INVALID_OTP_REQUEST', message: parsed.error.issues[0]?.message ?? 'Invalid OTP request' }); if (env.OTP_PROVIDER !== 'msg91') return reply.code(503).send({ error: 'OTP_PROVIDER_NOT_CONFIGURED' }); const phone = normalizePhone(parsed.data.phone); const user = await prisma.user.findFirst({ where: { phone: { in: phoneCandidates(phone) }, isActive: true, deletedAt: null }, select: userSelect() }); if (!user) return reply.code(404).send({ error: 'ACCOUNT_NOT_FOUND', message: 'No account was found for this mobile number.' }); const verification = await verifyAccessToken(parsed.data.accessToken, user.phone); if (!verification.verified) { request.log.warn({ reason: verification.reason, httpStatus: verification.httpStatus, responseType: verification.responseType, responseKeys: verification.responseKeys }, 'MSG91 access-token verification failed'); return reply.code(401).send({ error: 'INVALID_OTP_TOKEN', message: 'Phone verification could not be confirmed.' }); } const verifiedUser = await prisma.user.update({ where: { id: user.id }, data: { isPhoneVerified: true, lastLoginAt: new Date() }, select: userSelect() }); const accessToken = await reply.jwtSign({ sub: verifiedUser.id, role: verifiedUser.role }, { expiresIn: '7d' }); return { accessToken, tokenType: 'Bearer', expiresIn: '7d', user: verifiedUser }; });
app.post('/dev-login', async (request, reply) => { if (env.NODE_ENV === 'production') return reply.code(404).send({ error: 'NOT_FOUND' }); const parsed = devLoginSchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: 'INVALID_DEV_LOGIN', message: parsed.error.issues[0]?.message ?? 'Invalid development login request' }); const { phone, firstName, lastName, role } = parsed.data; const user = await prisma.user.upsert({ where: { phone }, update: { ...(firstName !== undefined ? { firstName } : {}), ...(lastName !== undefined ? { lastName } : {}), role, isPhoneVerified: true, isActive: true, deletedAt: null, lastLoginAt: new Date() }, create: { phone, firstName, lastName, role, isPhoneVerified: true, lastLoginAt: new Date() }, select: userSelect() }); const accessToken = await reply.jwtSign({ sub: user.id, role: user.role }, { expiresIn: '7d' }); return { accessToken, tokenType: 'Bearer', expiresIn: '7d', user }; });
app.get('/me', async (request, reply) => { try { const payload = await request.jwtVerify<{ sub: string }>(); const user = await prisma.user.findFirst({ where: { id: payload.sub, isActive: true, deletedAt: null }, select: { ...userSelect(), createdAt: true } }); if (!user) return reply.code(404).send({ error: 'USER_NOT_FOUND' }); return { user }; } catch { return reply.code(401).send({ error: 'UNAUTHORIZED', message: 'A valid access token is required.' }); } });
}
