import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useLanguageText } from '@/hooks/use-language-text';

const C={maroon:'#7A1024',gold:'#C99A3D',paper:'#FFF9EF',ink:'#2F2020',muted:'#7B6865'};
const faqs=[
['अकाउंट कैसे बनाएँ या लॉगिन करें?','Profile टैब में नया अकाउंट बनाएँ या लॉगिन चुनें और मांगी गई जानकारी भरें।','How do I create an account or log in?','Open Profile, choose Create account or Login, and enter the requested details.'],
['ऐप की भाषा कैसे बदलें?','Settings में Language से हिन्दी या English चुनें।','How do I change the app language?','Choose Hindi or English under Language in Settings.'],
['मैट्रिमोनी प्रोफाइल कैसे जोड़ें?','Profile → मेरे मैट्रिमोनी प्रोफाइल में नया प्रोफाइल जोड़ें। जानकारी और फोटो भरकर approval के लिए भेजें।','How do I add a matrimony profile?','Open Profile → My matrimony profiles, add a profile, fill in details and photos, then submit for approval.'],
['मैट्रिमोनी प्रोफाइल कैसे अपडेट करें?','मेरे मैट्रिमोनी प्रोफाइल में अपना प्रोफाइल खोलें और उपलब्ध edit विकल्प से जानकारी बदलें। बदलाव approval के अधीन हो सकते हैं।','How do I update a matrimony profile?','Open your profile under My matrimony profiles and use the available edit option. Changes may require approval.'],
['प्रोफाइल तुरंत क्यों नहीं दिख रहा?','नई या बदली जानकारी पहले admin review में जाती है। Approval के बाद approved profile public listing में दिखाई देता है।','Why is my profile not visible immediately?','New or changed information is reviewed by an admin first and appears publicly after approval.'],
['मैट्रिमोनी प्रोफाइल कैसे देखें?','Matrimony टैब या Home के matrimony section से profile चुनें। Detail देखने के लिए login जरूरी हो सकता है।','How do I view matrimony profiles?','Choose a profile from the Matrimony tab or Home. Login may be required to view details.'],
['Interest कैसे भेजें या accept करें?','Profile detail में Interest विकल्प से request भेजें। प्राप्त interests को अपने matrimony section से manage करें।','How do I send or accept an interest?','Use Interest on a profile to send a request and manage received interests from your matrimony section.'],
['समाचार कैसे जोड़ें?','Community में समाचार category खोलकर Add चुनें। शीर्षक, विवरण, image और जरूरी जानकारी भरकर approval के लिए भेजें।','How do I add news?','Open News in Community, choose Add, enter the details and image, then submit for approval.'],
['समाज की जानकारी कहाँ देखें?','Community में approved समाचार, कार्यक्रम, शोक सूचना और दूसरी उपलब्ध categories देख सकते हैं।','Where can I view community updates?','Open Community to view approved news, events, obituary notices and other available categories.'],
['कार्यक्रम कैसे जोड़ें?','Community में कार्यक्रम से Add चुनें। तारीख, स्थान और विवरण भरकर submit करें।','How do I add an event?','Choose Add under Events in Community, enter the date, location and details, then submit.'],
['शोक सूचना कैसे जोड़ें?','Community → शोक सूचना → Add में प्रकार, नाम, तारीख, कार्यक्रम जानकारी और image भरकर approval के लिए भेजें।','How do I add an obituary notice?','Open Community → Obituary → Add, enter the notice details and image, then submit for approval.'],
['शोक सूचना की notification कब मिलती है?','नई शोक सूचना admin द्वारा approve और publish होने पर registered devices पर notification भेजी जाती है।','When do obituary notifications arrive?','A notification is sent to registered devices when a new obituary notice is approved and published.'],
['विज्ञापन कैसे जोड़ें?','Community में विज्ञापन category से Add चुनें और जानकारी submit करें। Approval के बाद विज्ञापन दिखाई देगा।','How do I add an advertisement?','Choose Add under Advertisement in Community and submit the details. It appears after approval.'],
['समिति कैसे जोड़ें या देखें?','समिति टैब में approved समितियाँ देखें। नई समिति के लिए समिति जोड़ें विकल्प इस्तेमाल करें।','How do I add or view a committee?','View approved committees in the Committee tab and use Add Committee to submit a new one.'],
['Submission तुरंत public क्यों नहीं होती?','सुरक्षा और सही जानकारी के लिए user submissions पहले admin approval में जाती हैं।','Why is a submission not public immediately?','For safety and information quality, user submissions go through admin approval first.'],
['Submission reject होने पर क्या होगा?','Rejected content public नहीं होगा। जरूरी सुधार करके उपलब्ध विकल्प के अनुसार दोबारा submit करें।','What happens if a submission is rejected?','Rejected content is not published. Correct the information and resubmit when the option is available.'],
['Notification नहीं आ रही तो क्या करें?','Phone Settings में Damodar Prayas की notification permission चालू रखें, internet जाँचें और app में login रहें।','What if notifications are not arriving?','Enable Damodar Prayas notifications in phone settings, check internet access and stay logged in.'],
['फोटो या image कैसे जोड़ें?','जहाँ upload उपलब्ध है वहाँ इमेज चुनें पर tap करके gallery से supported image चुनें और form submit करें।','How do I add a photo or image?','Tap Choose image where upload is available, select a supported gallery image and submit the form.'],
['क्या submitted content सीधे दिखाई देता है?','नहीं। Matrimony, समाचार, कार्यक्रम, शोक सूचना, विज्ञापन और समिति जैसी submissions approval के बाद public होती हैं।','Does submitted content appear immediately?','No. Matrimony, news, events, obituary notices, advertisements and committees become public after approval.'],
['और मदद चाहिए तो क्या करें?','पहले संबंधित FAQ देखें। समस्या बनी रहे तो समाज/admin support से संपर्क करें और समस्या का स्पष्ट विवरण दें।','What if I still need help?','Check the related FAQ first. If the issue remains, contact community/admin support with a clear description.'],
] as const;
export default function FaqScreen(){const {language}=useLanguageText();const [open,setOpen]=useState<number|null>(null);const hi=language==='hi';return <SafeAreaView style={s.safe}><View style={s.header}><Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>‹</Text></Pressable><View style={s.headCopy}><Text style={s.title}>{hi?'सहायता और सवाल':'Help & FAQ'}</Text><Text style={s.subtitle}>{hi?'Damodar Prayas इस्तेमाल करने की आसान जानकारी':'Quick help for using Damodar Prayas'}</Text></View></View><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><View style={s.intro}><Text style={s.introTitle}>{hi?'Damodar Prayas कैसे इस्तेमाल करें?':'How to use Damodar Prayas'}</Text><Text style={s.introText}>{hi?'किसी सवाल पर tap करें, जवाब नीचे खुल जाएगा।':'Tap any question to expand its answer.'}</Text></View>{faqs.map((f,i)=>{const active=open===i;return <Pressable key={i} style={s.item} onPress={()=>setOpen(active?null:i)}><View style={s.qrow}><Text style={s.question}>{hi?f[0]:f[2]}</Text><Text style={s.plus}>{active?'−':'+'}</Text></View>{active?<Text style={s.answer}>{hi?f[1]:f[3]}</Text>:null}</Pressable>})}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.paper},header:{paddingHorizontal:18,height:76,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:'#EEDFCF'},headCopy:{flex:1},back:{width:40,height:40,borderRadius:20,alignItems:'center',justifyContent:'center',backgroundColor:'#F5E9DC'},backText:{fontSize:32,lineHeight:34,color:C.maroon},title:{fontSize:22,fontWeight:'900',color:C.maroon},subtitle:{fontSize:12,color:C.muted,marginTop:2},content:{padding:18,paddingBottom:40},intro:{padding:17,borderRadius:18,backgroundColor:'#FFF3D9',borderWidth:1,borderColor:'#E8CF98',marginBottom:14},introTitle:{fontSize:17,fontWeight:'900',color:C.maroon},introText:{fontSize:13,lineHeight:19,color:C.muted,marginTop:5},item:{backgroundColor:'#FFF',borderWidth:1,borderColor:'#EEDFCF',borderRadius:16,padding:16,marginBottom:10},qrow:{flexDirection:'row',alignItems:'center',gap:12},question:{flex:1,fontSize:15,fontWeight:'800',lineHeight:21,color:C.ink},plus:{fontSize:24,fontWeight:'600',color:C.gold},answer:{marginTop:12,paddingTop:12,borderTopWidth:1,borderTopColor:'#F0E4D8',fontSize:14,lineHeight:21,color:C.muted}});
