// Source: https://pmay-urban.gov.in/uploads/List-of-ULB.pdf
// Retrieved 2026-09-26. Madhya Pradesh ULBs (including cantonments); excludes planning areas/villages.
export const mpCities: { id: string; name: string; district: string }[] = [
  {"id": "250858", "name": "Agar", "district": "Agar-Malwa"},
  {"id": "250749", "name": "Ajaigarh", "district": "Panna"},
  {"id": "250685", "name": "Akoda", "district": "Bhind"},
  {"id": "250863", "name": "Akodia", "district": "Shajapur"},
  {"id": "250692", "name": "Alampur", "district": "Bhind"},
  {"id": "250882", "name": "Alirajpur", "district": "Alirajpur"},
  {"id": "250839", "name": "Alot", "district": "Ratlam"},
  {"id": "250753", "name": "Amanganj", "district": "Panna"},
  {"id": "253195", "name": "Amarkantak", "district": "Anuppur"},
  {"id": "250786", "name": "Amarpatan", "district": "Maihar"},
  {"id": "251008", "name": "Amarwara", "district": "Chhindwara"},
  {"id": "250675", "name": "Ambah", "district": "Morena"},
  {"id": "248073", "name": "Amla", "district": "Betul"},
  {"id": "250915", "name": "Anjad", "district": "Barwani"},
  {"id": "250699", "name": "Antari", "district": "Gwalior"},
  {"id": "265847", "name": "Anuppur", "district": "Anuppur"},
  {"id": "250719", "name": "Aron", "district": "Guna"},
  {"id": "250715", "name": "Ashoknagar", "district": "Ashoknagar"},
  {"id": "250949", "name": "Ashta (M)", "district": "Sehore"},
  {"id": "293817", "name": "Athana", "district": "Neemuch"},
  {"id": "263361", "name": "Athner", "district": "Betul"},
  {"id": "250975", "name": "Babai", "district": "Narmadapuram"},
  {"id": "250744", "name": "Bada Malhera", "district": "Chhatarpur"},
  {"id": "250733", "name": "Badagaon (Agar)", "district": "Agar-Malwa"},
  {"id": "290258", "name": "Badagaon (Tikamgarh)", "district": "Tikamgarh"},
  {"id": "250709", "name": "Badarwas", "district": "Shivpuri"},
  {"id": "250838", "name": "Badawada", "district": "Ratlam"},
  {"id": "250961", "name": "Badi", "district": "Raisen"},
  {"id": "251025", "name": "Badkuhi", "district": "Chhindwara"},
  {"id": "250852", "name": "Badnagar", "district": "Ujjain"},
  {"id": "250884", "name": "Badnawar", "district": "Dhar"},
  {"id": "250857", "name": "Badod", "district": "Agar-Malwa"},
  {"id": "250674", "name": "Badoda", "district": "Sheopur"},
  {"id": "277237", "name": "Badoni", "district": "Datia"},
  {"id": "290389", "name": "Bagli", "district": "Dewas"},
  {"id": "251041", "name": "Baihar", "district": "Balaghat"},
  {"id": "250792", "name": "Baikunthpur", "district": "Rewa"},
  {"id": "298926", "name": "Bakho", "district": "Shahdol"},
  {"id": "251040", "name": "Balaghat", "district": "Balaghat"},
  {"id": "290276", "name": "Baldeogarh", "district": "Tikamgarh"},
  {"id": "289260", "name": "Bamhani", "district": "Mandla"},
  {"id": "250678", "name": "Bamor", "district": "Morena"},
  {"id": "250760", "name": "Banda (Sagar)", "district": "Sagar"},
  {"id": "297114", "name": "Bandri", "district": "Sagar"},
  {"id": "263020", "name": "Bankhedi", "district": "Narmadapuram"},
  {"id": "250962", "name": "Baraily", "district": "Raisen"},
  {"id": "250997", "name": "Barela", "district": "Jabalpur"},
  {"id": "300395", "name": "Bargawan", "district": "Singrauli"},
  {"id": "299804", "name": "Bargawan (Amlai)", "district": "Anuppur"},
  {"id": "251034", "name": "Barghat", "district": "Seoni"},
  {"id": "250978", "name": "Barhi", "district": "Katni"},
  {"id": "250734", "name": "Barigarh", "district": "Chhatarpur"},
  {"id": "501381", "name": "Barkoda", "district": "Shahdol"},
  {"id": "300085", "name": "Barodiya Kalan", "district": "Sagar"},
  {"id": "250907", "name": "Barwaha", "district": "Khargone (West Nimar)"},
  {"id": "250914", "name": "Barwani", "district": "Barwani"},
  {"id": "293809", "name": "Basoda", "district": "Vidisha"},
  {"id": "250957", "name": "Begamganj", "district": "Raisen"},
  {"id": "250805", "name": "Beohari", "district": "Shahdol"},
  {"id": "263211", "name": "Beraidh", "district": "Shivpuri"},
  {"id": "250945", "name": "Berasia", "district": "Bhopal"},
  {"id": "250897", "name": "Betma", "district": "Indore"},
  {"id": "248072", "name": "Betul", "district": "Betul"},
  {"id": "248070", "name": "Betul-Bazar", "district": "Betul"},
  {"id": "250964", "name": "Bhainsdehi", "district": "Betul"},
  {"id": "250704", "name": "Bhander", "district": "Datia"},
  {"id": "250827", "name": "Bhanpura", "district": "Mandsaur"},
  {"id": "250865", "name": "Bhaurasa", "district": "Dewas"},
  {"id": "250880", "name": "Bhavra", "district": "Alirajpur"},
  {"id": "250996", "name": "Bhedaghat", "district": "Jabalpur"},
  {"id": "298922", "name": "Bhensoda", "district": "Mandsaur"},
  {"id": "250912", "name": "Bhikangaon", "district": "Khargone (West Nimar)"},
  {"id": "250684", "name": "Bhind", "district": "Bhind"},
  {"id": "250700", "name": "Bhitarwar", "district": "Gwalior"},
  {"id": "250946", "name": "Bhopal", "district": "Bhopal"},
  {"id": "250934", "name": "Biaora", "district": "Rajgarh"},
  {"id": "253171", "name": "Bichhiya", "district": "Mandla"},
  {"id": "263072", "name": "Bichua", "district": "Chhindwara"},
  {"id": "250747", "name": "Bijawar", "district": "Chhatarpur"},
  {"id": "253194", "name": "Bijuri", "district": "Anuppur"},
  {"id": "250695", "name": "Bilaua", "district": "Gwalior"},
  {"id": "298917", "name": "Bilehra", "district": "Sagar"},
  {"id": "250755", "name": "Bina- Etawa", "district": "Sagar"},
  {"id": "250778", "name": "Birsinghpur", "district": "Satna"},
  {"id": "298931", "name": "Bistan", "district": "Khargone (West Nimar)"},
  {"id": "250938", "name": "Boda", "district": "Rajgarh"},
  {"id": "250952", "name": "Budni", "district": "Sehore"},
  {"id": "250925", "name": "Burhanpur", "district": "Burhanpur"},
  {"id": "250808", "name": "Burhar", "district": "Shahdol"},
  {"id": "250748", "name": "Buxwaha", "district": "Chhatarpur"},
  {"id": "250720", "name": "Chachaura-Binaganj", "district": "Guna"},
  {"id": "250788", "name": "Chakghat", "district": "Rewa"},
  {"id": "250756", "name": "Chand", "district": "Chhindwara"},
  {"id": "251023", "name": "Chandameta- Butaria", "district": "Chhindwara"},
  {"id": "250713", "name": "Chanderi", "district": "Ashoknagar"},
  {"id": "250800", "name": "Chandia", "district": "Umaria"},
  {"id": "250736", "name": "Chandla", "district": "Chhatarpur"},
  {"id": "251009", "name": "Chaurai Khas", "district": "Chhindwara"},
  {"id": "250920", "name": "Chhanera", "district": "Khandwa (East Nimar)"},
  {"id": "298932", "name": "Chhapara", "district": "Seoni"},
  {"id": "262992", "name": "Chhapiheda", "district": "Rajgarh"},
  {"id": "250741", "name": "Chhatarpur", "district": "Chhatarpur"},
  {"id": "251026", "name": "Chhindwara", "district": "Chhindwara"},
  {"id": "251000", "name": "Chichli", "district": "Narsimhapur"},
  {"id": "263218", "name": "Chicholi", "district": "Betul"},
  {"id": "250777", "name": "Chitrakoot", "district": "Satna"},
  {"id": "248068", "name": "Churhat", "district": "Sidhi"},
  {"id": "298925", "name": "Dabhaura", "district": "Rewa"},
  {"id": "250693", "name": "Daboh", "district": "Bhind"},
  {"id": "250698", "name": "Dabra", "district": "Gwalior"},
  {"id": "290394", "name": "Dahi", "district": "Dhar"},
  {"id": "250774", "name": "Damoh", "district": "Damoh"},
  {"id": "293808", "name": "Damua", "district": "Chhindwara"},
  {"id": "250703", "name": "Datia", "district": "Datia"},
  {"id": "250770", "name": "Deori (M)", "district": "Sagar"},
  {"id": "250896", "name": "Depalpur", "district": "Indore"},
  {"id": "250751", "name": "Devendranagar", "district": "Panna"},
  {"id": "250815", "name": "Devri", "district": "Raisen"},
  {"id": "250867", "name": "Dewas", "district": "Dewas"},
  {"id": "290379", "name": "Dhamnod (Dhar)", "district": "Dhar"},
  {"id": "250893", "name": "Dhamnod (Ratlam)", "district": "Ratlam"},
  {"id": "250809", "name": "Dhanpuri", "district": "Shahdol"},
  {"id": "250887", "name": "Dhar", "district": "Dhar"},
  {"id": "250894", "name": "Dharampuri", "district": "Dhar"},
  {"id": "250821", "name": "Diken", "district": "Neemuch"},
  {"id": "290390", "name": "Dindori (NP)", "district": "Dindori"},
  {"id": "298927", "name": "Dola", "district": "Anuppur"},
  {"id": "251022", "name": "Dongar Parasia", "district": "Chhindwara"},
  {"id": "298928", "name": "Dumar Kachhar", "district": "Anuppur"},
  {"id": "250999", "name": "Gadarwara", "district": "Narsimhapur"},
  {"id": "250956", "name": "Gairatganj", "district": "Raisen"},
  {"id": "250768", "name": "Garhakota", "district": "Sagar"},
  {"id": "250739", "name": "Garhi - Malhera", "district": "Chhatarpur"},
  {"id": "250831", "name": "Garoth", "district": "Mandsaur"},
  {"id": "298919", "name": "Ghodadongri", "district": "Betul"},
  {"id": "250745", "name": "Ghuwara", "district": "Chhatarpur"},
  {"id": "250688", "name": "Gohad", "district": "Bhind"},
  {"id": "250686", "name": "Gormi", "district": "Bhind"},
  {"id": "250998", "name": "Gotegaon", "district": "Narsimhapur"},
  {"id": "250798", "name": "Govindgarh (TP)", "district": "Rewa"},
  {"id": "250714", "name": "Guna", "district": "Guna"},
  {"id": "297930", "name": "Gunaur", "district": "Panna"},
  {"id": "250799", "name": "Gurh", "district": "Rewa"},
  {"id": "250694", "name": "Gwalior", "district": "Gwalior"},
  {"id": "250794", "name": "Hanumana", "district": "MAUGANJ"},
  {"id": "250967", "name": "Harda", "district": "Harda"},
  {"id": "250737", "name": "Harpalpur", "district": "Chhatarpur"},
  {"id": "251007", "name": "Harrai", "district": "Chhindwara"},
  {"id": "250900", "name": "Hatod", "district": "Indore"},
  {"id": "250872", "name": "Hatpiplya", "district": "Dewas"},
  {"id": "250771", "name": "Hatta", "district": "Damoh"},
  {"id": "250773", "name": "Hindoria", "district": "Damoh"},
  {"id": "250974", "name": "Hoshangabad", "district": "Narmadapuram"},
  {"id": "250950", "name": "Ichhawar", "district": "Sehore"},
  {"id": "250702", "name": "Indergarh", "district": "Datia"},
  {"id": "250901", "name": "Indore", "district": "Indore"},
  {"id": "250712", "name": "Isagarh", "district": "Ashoknagar"},
  {"id": "250970", "name": "Itarsi", "district": "Narmadapuram"},
  {"id": "250995", "name": "Jabalpur", "district": "Jabalpur"},
  {"id": "277265", "name": "Jabalpur Cantt (CB)", "district": "Jabalpur"},
  {"id": "250806", "name": "Jaisinghnagar", "district": "Shahdol"},
  {"id": "253196", "name": "Jaithari", "district": "Anuppur"},
  {"id": "250780", "name": "Jaitwara", "district": "Satna"},
  {"id": "251010", "name": "Jamai", "district": "Chhindwara"},
  {"id": "250837", "name": "Jaora", "district": "Ratlam"},
  {"id": "290257", "name": "Jatara", "district": "Tikamgarh"},
  {"id": "250822", "name": "Jawad", "district": "Neemuch"},
  {"id": "250948", "name": "Jawar", "district": "Sehore"},
  {"id": "290323", "name": "Jeron Khalsa", "district": "Niwari"},
  {"id": "250879", "name": "Jhabua", "district": "Jhabua"},
  {"id": "250681", "name": "Jhundpura", "district": "Morena"},
  {"id": "250824", "name": "Jiran", "district": "Neemuch"},
  {"id": "250929", "name": "Jirapur", "district": "Rajgarh"},
  {"id": "250881", "name": "Jobat", "district": "Alirajpur"},
  {"id": "250679", "name": "Joura", "district": "Morena"},
  {"id": "293822", "name": "Kaarahi and Pandlyakhurd", "district": "Khargone (West Nimar)"},
  {"id": "250680", "name": "Kailaras", "district": "Morena"},
  {"id": "250752", "name": "Kakarhati", "district": "Panna"},
  {"id": "250859", "name": "Kanad", "district": "Agar-Malwa"},
  {"id": "250868", "name": "Kannod", "district": "Dewas"},
  {"id": "250870", "name": "Kantaphod", "district": "Dewas"},
  {"id": "251002", "name": "Kareli", "district": "Narsimhapur"},
  {"id": "250707", "name": "Karera", "district": "Shivpuri"},
  {"id": "290256", "name": "Kari", "district": "Tikamgarh"},
  {"id": "250873", "name": "Karnawad", "district": "Dewas"},
  {"id": "300387", "name": "Karrapur", "district": "Sagar"},
  {"id": "250911", "name": "Kasrawad", "district": "Khargone (West Nimar)"},
  {"id": "251035", "name": "Katangi (Balaghat)", "district": "Balaghat"},
  {"id": "250984", "name": "Katangi (Jabalpur)", "district": "Jabalpur"},
  {"id": "298933", "name": "Keolari (CT)", "district": "Seoni"},
  {"id": "250845", "name": "Khacharod", "district": "Ujjain"},
  {"id": "250743", "name": "Khajuraho", "district": "Chhatarpur"},
  {"id": "250804", "name": "Khand (Bansagar)", "district": "Shahdol"},
  {"id": "250923", "name": "Khandwa (East Nimar)", "district": "Khandwa (East Nimar)"},
  {"id": "250711", "name": "Khaniyadhana", "district": "Shivpuri"},
  {"id": "290306", "name": "Khargapur", "district": "Tikamgarh"},
  {"id": "250913", "name": "Khargone (West Nimar)", "district": "Khargone (West Nimar)"},
  {"id": "250875", "name": "Khategaon", "district": "Dewas"},
  {"id": "250918", "name": "Khetia", "district": "Barwani"},
  {"id": "250930", "name": "Khilchipur", "district": "Rajgarh"},
  {"id": "250966", "name": "Khirkiya", "district": "Harda"},
  {"id": "250932", "name": "Khujner", "district": "Rajgarh"},
  {"id": "250758", "name": "Khurai", "district": "Sagar"},
  {"id": "802313", "name": "Kolar (Bhopal)", "district": "Bhopal"},
  {"id": "250708", "name": "Kolaras", "district": "Shivpuri"},
  {"id": "250784", "name": "Kotar", "district": "Satna"},
  {"id": "250779", "name": "Kothi", "district": "Satna"},
  {"id": "290383", "name": "Kothri", "district": "Sehore"},
  {"id": "253193", "name": "Kotma", "district": "Anuppur"},
  {"id": "253134", "name": "Kukdeshwar", "district": "Neemuch"},
  {"id": "250891", "name": "Kukshi", "district": "Dhar"},
  {"id": "250718", "name": "Kumbhraj", "district": "Guna"},
  {"id": "262908", "name": "Kurawar", "district": "Rajgarh"},
  {"id": "250942", "name": "Kurwai", "district": "Vidisha"},
  {"id": "250980", "name": "Kymore", "district": "Katni"},
  {"id": "250691", "name": "Lahar", "district": "Bhind"},
  {"id": "251031", "name": "Lakhnadon", "district": "Seoni"},
  {"id": "253162", "name": "Lanji", "district": "Balaghat"},
  {"id": "250940", "name": "Lateri", "district": "Vidisha"},
  {"id": "250735", "name": "Laundi", "district": "Chhatarpur"},
  {"id": "290253", "name": "Lidhora Khas", "district": "Tikamgarh"},
  {"id": "251029", "name": "Lodhikheda", "district": "Chhindwara"},
  {"id": "250869", "name": "Loharda", "district": "Dewas"},
  {"id": "250928", "name": "Machalpur", "district": "Rajgarh"},
  {"id": "299299", "name": "Magroni", "district": "Shivpuri"},
  {"id": "250740", "name": "Maharajpur", "district": "Chhatarpur"},
  {"id": "250909", "name": "Maheshwar", "district": "Khargone (West Nimar)"},
  {"id": "250849", "name": "Mahidpur", "district": "Ujjain"},
  {"id": "250787", "name": "Maihar", "district": "Maihar"},
  {"id": "250818", "name": "Majhauli", "district": "Sidhi"},
  {"id": "250982", "name": "Majholi", "district": "Jabalpur"},
  {"id": "263205", "name": "Makdon", "district": "Ujjain"},
  {"id": "250766", "name": "Makronia Buzurg", "district": "Sagar"},
  {"id": "250861", "name": "Maksi", "district": "Shajapur"},
  {"id": "299255", "name": "Maksudangarh", "district": "Guna"},
  {"id": "251042", "name": "Malajkhand", "district": "Balaghat"},
  {"id": "298924", "name": "Malanpur (CT)", "district": "Bhind"},
  {"id": "250828", "name": "Malhargarh", "district": "Mandsaur"},
  {"id": "297116", "name": "Malthon", "district": "Sagar"},
  {"id": "250826", "name": "Manasa", "district": "Neemuch"},
  {"id": "250892", "name": "Manawar", "district": "Dhar"},
  {"id": "250889", "name": "Mandav", "district": "Dhar"},
  {"id": "250959", "name": "Mandideep", "district": "Raisen"},
  {"id": "289259", "name": "Mandla (M)", "district": "Mandla"},
  {"id": "250910", "name": "Mandleshwar", "district": "Khargone (West Nimar)"},
  {"id": "250833", "name": "Mandsaur", "district": "Mandsaur"},
  {"id": "250793", "name": "Mangawan", "district": "Rewa"},
  {"id": "250906", "name": "Manpur (Indore)", "district": "Indore"},
  {"id": "297136", "name": "Manpurr", "district": "Umaria"},
  {"id": "250689", "name": "Mau", "district": "Bhind"},
  {"id": "250796", "name": "Mauganj", "district": "MAUGANJ"},
  {"id": "273379", "name": "Meghnagar", "district": "Jhabua"},
  {"id": "290392", "name": "Mehgaon", "district": "Bhind"},
  {"id": "277272", "name": "Mhow Cantt (CB)", "district": "Indore"},
  {"id": "250905", "name": "Mhowgaon", "district": "Indore"},
  {"id": "250690", "name": "Mihona", "district": "Bhind"},
  {"id": "299289", "name": "Mohana", "district": "Gwalior"},
  {"id": "251028", "name": "Mohgaon", "district": "Pandhurna"},
  {"id": "277296", "name": "Morar Cantt (CB)", "district": "Gwalior"},
  {"id": "250677", "name": "Morena", "district": "Morena"},
  {"id": "248071", "name": "Multai", "district": "Betul"},
  {"id": "250922", "name": "Mundi", "district": "Khandwa (East Nimar)"},
  {"id": "250717", "name": "Mungaoli", "district": "Ashoknagar"},
  {"id": "250979", "name": "Murwara (Katni)", "district": "Katni"},
  {"id": "250846", "name": "Nagda", "district": "Ujjain"},
  {"id": "250782", "name": "Nagod", "district": "Satna"},
  {"id": "250834", "name": "Nagri", "district": "Mandsaur"},
  {"id": "250795", "name": "Naigarhi", "district": "MAUGANJ"},
  {"id": "248075", "name": "Nainpur", "district": "Mandla"},
  {"id": "250855", "name": "Nalkheda", "district": "Agar-Malwa"},
  {"id": "250842", "name": "Namli", "district": "Ratlam"},
  {"id": "250829", "name": "Narayangarh", "district": "Mandsaur"},
  {"id": "251001", "name": "Narsimhapur", "district": "Narsimhapur"},
  {"id": "250937", "name": "Narsinghgarh", "district": "Rajgarh"},
  {"id": "250706", "name": "Narwar", "district": "Shivpuri"},
  {"id": "250951", "name": "Nasrullaganj", "district": "Sehore"},
  {"id": "263154", "name": "Nayagaon (Neemuch)", "district": "Neemuch"},
  {"id": "250823", "name": "Neemuch", "district": "Neemuch"},
  {"id": "274350", "name": "Nemawar", "district": "Dewas"},
  {"id": "250927", "name": "Nepanagar", "district": "Burhanpur"},
  {"id": "251018", "name": "Neuton Chikhli Kalan", "district": "Chhindwara"},
  {"id": "293819", "name": "New Ramnagar", "district": "Satna"},
  {"id": "297118", "name": "Niwali Buzurg", "district": "Barwani"},
  {"id": "290382", "name": "Niwari (TP)", "district": "Niwari"},
  {"id": "253170", "name": "Niwas", "district": "Mandla"},
  {"id": "250738", "name": "Nowgong", "district": "Chhatarpur"},
  {"id": "250803", "name": "Nowrozabad (Khodargama)", "district": "Umaria"},
  {"id": "250960", "name": "Obedullaganj", "district": "Raisen"},
  {"id": "250921", "name": "Omkareshwar", "district": "Khandwa (East Nimar)"},
  {"id": "293827", "name": "Orchha", "district": "Niwari"},
  {"id": "277274", "name": "Pachmarhi Cantt (CB)", "district": "Narmadapuram"},
  {"id": "250935", "name": "Pachore", "district": "Rajgarh"},
  {"id": "290343", "name": "Palera", "district": "Tikamgarh"},
  {"id": "250802", "name": "Pali (Umaria)", "district": "Umaria"},
  {"id": "253251", "name": "Palsud", "district": "Barwani"},
  {"id": "250987", "name": "Panagar", "district": "Jabalpur"},
  {"id": "250924", "name": "Pandhana", "district": "Khandwa (East Nimar)"},
  {"id": "251030", "name": "Pandhurna", "district": "Pandhurna"},
  {"id": "263010", "name": "Pankhedi", "district": "Shajapur"},
  {"id": "250750", "name": "Panna", "district": "Panna"},
  {"id": "250917", "name": "Pansemal", "district": "Barwani"},
  {"id": "253197", "name": "Pasan", "district": "Anuppur"},
  {"id": "250985", "name": "Patan (TP)", "district": "Jabalpur"},
  {"id": "293826", "name": "Patera", "district": "Damoh"},
  {"id": "250772", "name": "Patharia", "district": "Damoh"},
  {"id": "250754", "name": "Pawai", "district": "Panna"},
  {"id": "250877", "name": "Petlawad", "district": "Jhabua"},
  {"id": "250683", "name": "Phuphkalan", "district": "Bhind"},
  {"id": "250697", "name": "Pichhore (Gwalior)", "district": "Gwalior"},
  {"id": "250710", "name": "Pichhore (Shivpuri)", "district": "Shivpuri"},
  {"id": "290272", "name": "Pipalrawan", "district": "Dewas"},
  {"id": "250977", "name": "Pipariya", "district": "Narmadapuram"},
  {"id": "290395", "name": "Piplanarayanwar", "district": "Chhindwara"},
  {"id": "250836", "name": "Piploda", "district": "Ratlam"},
  {"id": "250830", "name": "Piplya Mandi", "district": "Mandsaur"},
  {"id": "299252", "name": "Piprai", "district": "Ashoknagar"},
  {"id": "250888", "name": "Pithampur", "district": "Dhar"},
  {"id": "289710", "name": "Pohri", "district": "Shivpuri"},
  {"id": "250864", "name": "Polaykalan", "district": "Shajapur"},
  {"id": "250676", "name": "Porsa", "district": "Morena"},
  {"id": "293821", "name": "Prithvipur", "district": "Niwari"},
  {"id": "300388", "name": "Punasa", "district": "Khandwa (East Nimar)"},
  {"id": "250716", "name": "Raghogarh-Vijaypur", "district": "Guna"},
  {"id": "250761", "name": "Rahatgarh", "district": "Sagar"},
  {"id": "250955", "name": "Raisen", "district": "Raisen"},
  {"id": "250931", "name": "Rajgarh (Dhar)", "district": "Dhar"},
  {"id": "250885", "name": "Rajgarh (Rajgarh)", "district": "Rajgarh"},
  {"id": "250742", "name": "Rajnagar (Chhatarpur)", "district": "Chhatarpur"},
  {"id": "299278", "name": "Rajnagar Bangawan", "district": "Anuppur"},
  {"id": "250916", "name": "Rajpur", "district": "Barwani"},
  {"id": "250785", "name": "Rampur Baghelan", "district": "Satna"},
  {"id": "248067", "name": "Rampur Naikin", "district": "Sidhi"},
  {"id": "250825", "name": "Rampura", "district": "Neemuch"},
  {"id": "250883", "name": "Ranapur", "district": "Jhabua"},
  {"id": "298921", "name": "Rannod", "district": "Shivpuri"},
  {"id": "250820", "name": "Ratangarh (TP)", "district": "Neemuch"},
  {"id": "250843", "name": "Ratlam", "district": "Ratlam"},
  {"id": "250904", "name": "Rau", "district": "Indore"},
  {"id": "250769", "name": "Rehli", "district": "Sagar"},
  {"id": "250953", "name": "Rehti", "district": "Sehore"},
  {"id": "250797", "name": "Rewa", "district": "Rewa"},
  {"id": "298923", "name": "Roun (Bhind)", "district": "Bhind"},
  {"id": "250895", "name": "Runji -Gautampura", "district": "Indore"},
  {"id": "250682", "name": "Sabalgarh", "district": "Morena"},
  {"id": "250764", "name": "Sagar", "district": "Sagar"},
  {"id": "802160", "name": "Sagar Cantt (CB)", "district": "Sagar"},
  {"id": "263217", "name": "Saikheda", "district": "Narsimhapur"},
  {"id": "250841", "name": "Sailana", "district": "Ratlam"},
  {"id": "293820", "name": "Salichauka", "district": "Narsimhapur"},
  {"id": "250908", "name": "Sanawad", "district": "Khargone (West Nimar)"},
  {"id": "250954", "name": "Sanchi", "district": "Raisen"},
  {"id": "300386", "name": "Sarai", "district": "Singrauli"},
  {"id": "250936", "name": "Sarangpur", "district": "Rajgarh"},
  {"id": "250886", "name": "Sardarpur", "district": "Dhar"},
  {"id": "248069", "name": "Sarni", "district": "Betul"},
  {"id": "263155", "name": "Sarwaniya maharaj", "district": "Neemuch"},
  {"id": "250746", "name": "Satai", "district": "Chhatarpur"},
  {"id": "250781", "name": "Satna", "district": "Satna"},
  {"id": "250871", "name": "Satwas", "district": "Dewas"},
  {"id": "251027", "name": "Sausar", "district": "Pandhurna"},
  {"id": "250898", "name": "Sawer", "district": "Indore"},
  {"id": "250947", "name": "Sehore", "district": "Sehore"},
  {"id": "250791", "name": "Semaria", "district": "Rewa"},
  {"id": "250919", "name": "Sendhwa", "district": "Barwani"},
  {"id": "250701", "name": "Seondha", "district": "Datia"},
  {"id": "251033", "name": "Seoni", "district": "Seoni"},
  {"id": "250969", "name": "Seoni-Malwa", "district": "Narmadapuram"},
  {"id": "262977", "name": "Shadora", "district": "Ashoknagar"},
  {"id": "250807", "name": "Shahdol", "district": "Shahdol"},
  {"id": "262903", "name": "Shahganj", "district": "Sehore"},
  {"id": "250759", "name": "Shahgarh", "district": "Sagar"},
  {"id": "298920", "name": "Shahpur (Betul)", "district": "Betul"},
  {"id": "250986", "name": "Shahpur Burhanpur", "district": "Burhanpur"},
  {"id": "250965", "name": "Shahpur Sagar", "district": "Sagar"},
  {"id": "250926", "name": "Shahpura (Jabalpur)", "district": "Jabalpur"},
  {"id": "251003", "name": "Shahpura Dindori", "district": "Dindori"},
  {"id": "250860", "name": "Shajapur", "district": "Shajapur"},
  {"id": "250832", "name": "Shamgarh", "district": "Mandsaur"},
  {"id": "262993", "name": "Shamshabad (TP)", "district": "Vidisha"},
  {"id": "250673", "name": "Sheopur", "district": "Sheopur"},
  {"id": "250705", "name": "Shivpuri (M)", "district": "Shivpuri"},
  {"id": "250862", "name": "Shujalpur", "district": "Shajapur"},
  {"id": "248065", "name": "Sidhi", "district": "Sidhi"},
  {"id": "250983", "name": "Sihora", "district": "Jabalpur"},
  {"id": "253125", "name": "Silwani", "district": "Raisen"},
  {"id": "250819", "name": "Singoli", "district": "Neemuch"},
  {"id": "248066", "name": "Singrauli", "district": "Singrauli"},
  {"id": "298918", "name": "Sirali", "district": "Harda"},
  {"id": "250790", "name": "Sirmour", "district": "Rewa"},
  {"id": "250941", "name": "Sironj", "district": "Vidisha"},
  {"id": "250835", "name": "Sitamau", "district": "Mandsaur"},
  {"id": "250976", "name": "Sohagpur", "district": "Narmadapuram"},
  {"id": "250866", "name": "Sonkatch", "district": "Dewas"},
  {"id": "250853", "name": "Soyatkalan", "district": "Agar-Malwa"},
  {"id": "250958", "name": "Sultanpur (TP)", "district": "Raisen"},
  {"id": "298934", "name": "Surkhi", "district": "Sagar"},
  {"id": "250854", "name": "Susner", "district": "Agar-Malwa"},
  {"id": "250933", "name": "Suthaliya", "district": "Rajgarh"},
  {"id": "290381", "name": "Suwasara", "district": "Mandsaur"},
  {"id": "250840", "name": "Tal", "district": "Ratlam"},
  {"id": "250939", "name": "Talen", "district": "Rajgarh"},
  {"id": "250850", "name": "Tarana", "district": "Ujjain"},
  {"id": "293818", "name": "Tarichar Kalan", "district": "Niwari"},
  {"id": "290462", "name": "Tendukheda- Damoh", "district": "Damoh"},
  {"id": "290429", "name": "Tendukheda- Narsimhapur", "district": "Narsimhapur"},
  {"id": "250789", "name": "Teonthar", "district": "Rewa"},
  {"id": "250876", "name": "Thandla", "district": "Jhabua"},
  {"id": "297119", "name": "Theekri", "district": "Barwani"},
  {"id": "290285", "name": "Tikamgarh", "district": "Tikamgarh"},
  {"id": "250968", "name": "Timarni", "district": "Harda"},
  {"id": "290271", "name": "Tonk Khurd", "district": "Dewas"},
  {"id": "250963", "name": "Udaipura (TP)", "district": "Raisen"},
  {"id": "250851", "name": "Ujjain", "district": "Ujjain"},
  {"id": "250801", "name": "Umaria", "district": "Umaria"},
  {"id": "250783", "name": "Unchahara", "district": "Satna"},
  {"id": "250847", "name": "Unhel", "district": "Ujjain"},
  {"id": "250944", "name": "Vidisha", "district": "Vidisha"},
  {"id": "250672", "name": "Vijaypur", "district": "Sheopur"},
  {"id": "250981", "name": "Vijayraghavgarh", "district": "Katni"},
  {"id": "251037", "name": "Waraseoni", "district": "Balaghat"},
];
