'use client';

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import AdminSidebar from '@/components/admin-sidebar';
import { API_BASE_URL, clearAdminSession, getAdminToken, verifyAdminSession } from '@/lib/auth';

type Translation={language?:string;title?:string|null;details?:string|null};
type Ad={id:string;category:string;status:string;bannerUrl?:string|null;contactName?:string|null;contactPhone?:string|null;location?:string|null;expiresAt?:string|null;isFeatured?:boolean;createdAt:string;translations?:Translation[]};

async function api(path:string,options:RequestInit={}){const token=getAdminToken();if(!token)throw new Error('SESSION_EXPIRED');const headers:Record<string,string>={authorization:`Bearer ${token}`,accept:'application/json'};if(options.body)headers['content-type']='application/json';const response=await fetch(`${API_BASE_URL}${path}`,{...options,headers:{...headers,...(options.headers||{})},cache:'no-store'});const data=await response.json().catch(()=>({}));if(response.status===401||response.status===403)throw new Error('SESSION_EXPIRED');if(!response.ok)throw new Error(data?.message||data?.error||`Request failed (${response.status})`);return data;}
function titleOf(ad:Ad){return ad.translations?.find(t=>t.language==='HI')?.title||ad.translations?.find(t=>t.language==='EN')?.title||ad.translations?.[0]?.title||'Untitled Advertisement';}
function detailsOf(ad:Ad){return ad.translations?.find(t=>t.language==='HI')?.details||ad.translations?.find(t=>t.language==='EN')?.details||ad.translations?.[0]?.details||'';}

export default function AdvertisementsPage(){const router=useRouter();const[items,setItems]=useState<Ad[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState<string|null>(null);
const load=useCallback(async()=>{setLoading(true);setError(null);try{const admin=await verifyAdminSession();if(!admin){router.replace('/login');return;}const data=await api('/admin/posts?status=PENDING&category=ADVERTISEMENT&page=1&limit=50');const rows=(data.items||[]).filter((item:Ad)=>item.category==='ADVERTISEMENT');setItems(rows);}catch(e){if(e instanceof Error&&e.message==='SESSION_EXPIRED'){clearAdminSession();router.replace('/login');return;}setError(e instanceof Error?e.message:'Advertisement queue load failed');}finally{setLoading(false);}},[router]);
useEffect(()=>{void load();},[load]);
async function action(path:string,body?:unknown){setBusy(path);setError(null);try{await api(path,{method:'POST',body:body?JSON.stringify(body):undefined});await load();}catch(e){setError(e instanceof Error?e.message:'Action failed');}finally{setBusy(null);}}
function reject(id:string){const reason=window.prompt('Advertisement reject करने का कारण लिखें:');if(reason?.trim())void action(`/admin/posts/${id}/reject`,{reason:reason.trim()});}
return <div className="admin-shell"><AdminSidebar/><main className="main moderation-page"><div className="moderation-top"><div><Link href="/" className="back-link">← Dashboard</Link><p className="eyebrow">ADVERTISEMENT MODERATION</p><h1>Advertisements Approval Center</h1><p className="subtitle">समाज के advertisements public होने से पहले details, contact और banner review करें।</p></div><button className="small-btn" onClick={()=>void load()}>Refresh</button></div><div className="moderation-tabs"><button className="active">Pending Ads <b>{items.length}</b></button></div>{error?<div className="moderation-error">{error}</div>:null}{loading?<div className="empty-state">Advertisements load हो रहे हैं…</div>:<section className="moderation-list">{items.length===0?<div className="empty-state">कोई pending advertisement नहीं है।</div>:items.map(ad=>{const title=titleOf(ad);const details=detailsOf(ad);return <article className="moderation-card" key={ad.id}><div className="profile-summary">{ad.bannerUrl?<div className="profile-photo"><img src={ad.bannerUrl} alt=""/></div>:<div className="profile-photo"><span>AD</span></div>}<div><span className="danger-label" style={{color:'#765414',background:'#fff7e5'}}>ADVERTISEMENT</span><h2 style={{marginTop:8}}>{title}</h2>{details?<p>{details.length>220?`${details.slice(0,220)}…`:details}</p>:null}<small>{ad.location||'Location not provided'} • {ad.contactName||'Contact name not provided'}{ad.contactPhone?` • ${ad.contactPhone}`:''}</small></div></div>{ad.expiresAt?<div className="reason-box"><b>Expiry</b><p>{new Date(ad.expiresAt).toLocaleDateString('en-IN')}</p></div>:null}<div className="moderation-actions"><button disabled={!!busy} className="reject-action" onClick={()=>reject(ad.id)}>Reject</button><button disabled={!!busy} className="approve-action" onClick={()=>window.confirm(`“${title}” publish करें?`)&&void action(`/admin/posts/${ad.id}/approve`)}>Approve</button></div></article>})}</section>}</main></div>}
