'use client';

import { useCallback, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import AdminSidebar from '@/components/admin-sidebar';
import { API_BASE_URL, clearAdminSession, getAdminToken, verifyAdminSession } from '@/lib/auth';

type Status='OPEN'|'REVIEWING'|'RESOLVED'|'DISMISSED';
type Report={id:string;reason:string;details?:string|null;status:Status;adminNote?:string|null;resolvedAt?:string|null;createdAt:string;reporter:{id:string;phone:string;firstName?:string|null;lastName?:string|null};matrimonyProfile:{id:string;firstName:string;lastName:string;status:string;createdById:string}};
const reasonLabels:Record<string,string>={FAKE_PROFILE:'Fake Profile',WRONG_INFORMATION:'Wrong Information',INAPPROPRIATE_CONTENT:'Inappropriate Content',DUPLICATE_PROFILE:'Duplicate Profile',SPAM:'Spam',OTHER:'Other'};
async function api(path:string,options:RequestInit={}){const token=getAdminToken();if(!token)throw new Error('SESSION_EXPIRED');const headers:Record<string,string>={authorization:`Bearer ${token}`,accept:'application/json'};if(options.body)headers['content-type']='application/json';const response=await fetch(`${API_BASE_URL}${path}`,{...options,headers:{...headers,...(options.headers||{})},cache:'no-store'});const data=await response.json().catch(()=>({}));if(response.status===401||response.status===403)throw new Error('SESSION_EXPIRED');if(!response.ok)throw new Error(data?.message||data?.error||`Request failed (${response.status})`);return data;}
export default function ReportsPage(){const router=useRouter();const[status,setStatus]=useState<Status>('OPEN');const[items,setItems]=useState<Report[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState<string|null>(null);const[total,setTotal]=useState(0);
const load=useCallback(async()=>{setLoading(true);setError(null);try{const admin=await verifyAdminSession();if(!admin){router.replace('/login');return;}const data=await api(`/admin/reports?status=${status}&page=1&limit=50`);setItems(data.items||[]);setTotal(data.pagination?.total??data.items?.length??0);}catch(e){if(e instanceof Error&&e.message==='SESSION_EXPIRED'){clearAdminSession();router.replace('/login');return;}setError(e instanceof Error?e.message:'Reports load failed');}finally{setLoading(false);}},[router,status]);useEffect(()=>{void load();},[load]);
async function action(report:Report,verb:'review'|'resolve'|'dismiss'){let body:unknown=undefined;if(verb==='resolve'||verb==='dismiss'){const note=window.prompt(verb==='resolve'?'Resolution / admin note (optional):':'Dismissal note (optional):');if(note===null)return;body={adminNote:note.trim()||undefined};}if(!window.confirm(verb==='review'?'इस report को review में लें?':verb==='resolve'?'इस report को resolved mark करें?':'इस report को dismiss करें?'))return;setBusy(report.id);setError(null);try{await api(`/admin/reports/${report.id}/${verb}`,{method:'POST',body:body?JSON.stringify(body):undefined});await load();}catch(e){setError(e instanceof Error?e.message:'Action failed');}finally{setBusy(null);}}
return <div className="admin-shell"><AdminSidebar/><main className="main moderation-page"><div className="moderation-top"><div><p className="eyebrow">TRUST & SAFETY</p><h1>Reports / Moderation</h1><p className="subtitle">Reported matrimony profiles review करें और moderation decision record करें।</p></div><button className="small-btn" onClick={()=>void load()}>Refresh</button></div><div className="moderation-tabs">{(['OPEN','REVIEWING','RESOLVED','DISMISSED'] as Status[]).map(s=><button key={s} className={status===s?'active':''} onClick={()=>setStatus(s)}>{s.replace('_',' ')}{status===s?<b>{total}</b>:null}</button>)}</div>{error?<div className="moderation-error">{error}</div>:null}{loading?<div className="empty-state">Reports load हो रही हैं…</div>:<section className="moderation-list">{items.length===0?<div className="empty-state">इस status में कोई report नहीं है।</div>:items.map(report=>{const reporter=[report.reporter.firstName,report.reporter.lastName].filter(Boolean).join(' ')||report.reporter.phone;const profile=[report.matrimonyProfile.firstName,report.matrimonyProfile.lastName].filter(Boolean).join(' ');return <article className="moderation-card" key={report.id}><div className="profile-summary"><div className="profile-photo"><span>⚑</span></div><div style={{flex:1}}><span className="danger-label">{reasonLabels[report.reason]||report.reason}</span><h2 style={{marginTop:8}}>{profile}</h2><p>{report.details||'Reporter ने additional details नहीं दी हैं।'}</p><small>Reported by {reporter} • {report.reporter.phone} • {new Date(report.createdAt).toLocaleString('en-IN')}</small></div></div><div className="reason-box"><b>Profile status</b><p>{report.matrimonyProfile.status} • Profile ID: {report.matrimonyProfile.id}</p>{report.adminNote?<><b>Admin note</b><p>{report.adminNote}</p></>:null}</div><div className="moderation-actions">{report.status==='OPEN'?<><button disabled={busy===report.id} className="small-btn" onClick={()=>void action(report,'review')}>Start Review</button><button disabled={busy===report.id} className="reject-action" onClick={()=>void action(report,'dismiss')}>Dismiss</button><button disabled={busy===report.id} className="approve-action" onClick={()=>void action(report,'resolve')}>Resolve</button></>:report.status==='REVIEWING'?<><button disabled={busy===report.id} className="reject-action" onClick={()=>void action(report,'dismiss')}>Dismiss</button><button disabled={busy===report.id} className="approve-action" onClick={()=>void action(report,'resolve')}>Resolve</button></>:<span style={{fontSize:13,opacity:.7}}>Moderation completed{report.resolvedAt?` • ${new Date(report.resolvedAt).toLocaleString('en-IN')}`:''}</span>}</div></article>})}</section>}</main></div>}
