'use client';

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { API_BASE_URL, clearAdminSession, getAdminToken, verifyAdminSession } from '@/lib/auth';

type Translation={language:string;name:string;details?:string|null};
type Member={id:string;name:string;designationHi?:string|null;designationEn?:string|null;phone?:string|null;email?:string|null;photoUrl?:string|null};
type Committee={id:string;status:string;bannerUrl?:string|null;logoUrl?:string|null;city?:string|null;district?:string|null;state?:string|null;address?:string|null;phone?:string|null;email?:string|null;createdAt:string;translations:Translation[];members:Member[]};
const nav=[['⌂','Dashboard','/'],['♡','Matrimony','/matrimony'],['▤','Community','/community'],['◈','Samiti','/samiti'],['⌁','Advertisements','/community'],['⚑','Reports','#'],['◎','Users','#']];

async function api(path:string,options:RequestInit={}){const token=getAdminToken();if(!token)throw new Error('SESSION_EXPIRED');const headers:Record<string,string>={authorization:`Bearer ${token}`,accept:'application/json'};if(options.body)headers['content-type']='application/json';const response=await fetch(`${API_BASE_URL}${path}`,{...options,headers:{...headers,...(options.headers||{})}});const data=response.status===204?{}:await response.json().catch(()=>({}));if(response.status===401||response.status===403)throw new Error('SESSION_EXPIRED');if(!response.ok)throw new Error(data?.message||data?.error||`Request failed (${response.status})`);return data;}
function nameOf(c:Committee){return c.translations?.find(t=>t.language==='HI')?.name||c.translations?.find(t=>t.language==='EN')?.name||c.translations?.[0]?.name||'Untitled Samiti';}
function detailsOf(c:Committee){return c.translations?.find(t=>t.language==='HI')?.details||c.translations?.find(t=>t.language==='EN')?.details||c.translations?.[0]?.details||'';}

export default function SamitiModerationPage(){const router=useRouter();const[items,setItems]=useState<Committee[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState<string|null>(null);
const load=useCallback(async()=>{setLoading(true);setError(null);try{const admin=await verifyAdminSession();if(!admin){router.replace('/login');return;}const data=await api('/admin/committees?status=PENDING');setItems(data.items||[]);}catch(e){if(e instanceof Error&&e.message==='SESSION_EXPIRED'){clearAdminSession();router.replace('/login');return;}setError(e instanceof Error?e.message:'Samiti queue load failed');}finally{setLoading(false);}},[router]);
useEffect(()=>{void load();},[load]);
async function action(path:string,body?:unknown){setBusy(path);setError(null);try{await api(path,{method:'POST',body:body?JSON.stringify(body):undefined});await load();}catch(e){setError(e instanceof Error?e.message:'Action failed');}finally{setBusy(null);}}
function reject(id:string){const reason=window.prompt('समिति reject करने का कारण लिखें:');if(reason?.trim())void action(`/admin/committees/${id}/reject`,{reason:reason.trim()});}
return <div className="admin-shell"><aside className="sidebar"><div className="brand"><div className="brand-seal">DP</div><div><strong>दामोदर प्रयास</strong><span>ADMIN PORTAL</span></div></div><nav className="nav-list">{nav.map(([icon,label,href])=><Link className={label==='Samiti'?'nav-item active':'nav-item'} href={href} key={label}><span>{icon}</span>{label}</Link>)}</nav><div className="sidebar-note"><span>सुरक्षित प्रशासन</span><p>Approval-first moderation keeps community content trusted.</p></div></aside><main className="main moderation-page"><div className="moderation-top"><div><Link href="/" className="back-link">← Dashboard</Link><p className="eyebrow">SAMITI MODERATION</p><h1>समिति Approval Center</h1><p className="subtitle">नई समितियों की जानकारी और members review करके publish करें।</p></div><button className="small-btn" onClick={()=>void load()}>Refresh</button></div><div className="moderation-tabs"><button className="active">Pending Samiti <b>{items.length}</b></button></div>{error?<div className="moderation-error">{error}</div>:null}{loading?<div className="empty-state">Samiti queue load हो रही है…</div>:<section className="moderation-list">{items.length===0?<div className="empty-state">कोई pending Samiti नहीं है।</div>:items.map(c=>{const name=nameOf(c),details=detailsOf(c);return <article className="moderation-card" key={c.id}><div className="profile-summary">{c.logoUrl||c.bannerUrl?<div className="profile-photo"><img src={c.logoUrl||c.bannerUrl||''} alt=""/></div>:<div className="profile-photo"><span>{name[0]||'स'}</span></div>}<div><span className="danger-label" style={{color:'#765414',background:'#fff7e5'}}>SAMITI</span><h2 style={{marginTop:8}}>{name}</h2><p>{[c.city,c.district,c.state].filter(Boolean).join(', ')||'Location not provided'}</p>{details?<p>{details.length>180?`${details.slice(0,180)}…`:details}</p>:null}<small>{c.phone||'Phone not provided'}{c.email?` • ${c.email}`:''} • {c.members?.length||0} members</small></div></div>{c.members?.length?<div className="reason-box"><b>Committee Members</b><p>{c.members.slice(0,5).map(m=>`${m.name}${m.designationHi?` (${m.designationHi})`:m.designationEn?` (${m.designationEn})`:''}`).join(' • ')}{c.members.length>5?` • +${c.members.length-5} more`:''}</p></div>:null}<div className="moderation-actions"><button disabled={!!busy} className="reject-action" onClick={()=>reject(c.id)}>Reject</button><button disabled={!!busy} className="approve-action" onClick={()=>window.confirm(`“${name}” publish करें?`)&&void action(`/admin/committees/${c.id}/approve`)}>Approve</button></div></article>})}</section>}</main></div>}
